### ISSUE TITLE
Links to VAR ID in uniprot changed

### ISSUE THREAD

**Issue by carighi** [PROconsortium/PRoteinOntology#148]
**Describe the issue**
The VAR_ID link from variants in PRO goes to a dead link

**To Reproduce**
1. Go to 
https://proconsortium.org/cgi-bin/textsearch_pro?searchtype2=&searchtype=&tmp=&field0=ALLFLDS&query0=VAR_*&andor1=AND&field1=ALLFLDS&query1=&numPerPg=50&opt_dsp_list2=PRO_NAME_TXT%2CPRO_DEF_TXT%2CCATEGORY%2CPARENT&dspOptOn=0&numPerPg_opt=50&opt_dsp_list=Category&opt_dsp_list=PRO+Name&opt_dsp_list=PRO+Term+Definition&opt_dsp_list=Parent&opt_dsp_list=UniProtKB+ID&apply.x=13&apply.y=6&page=1&page_max=28&sortUp_hidden=&sortDown_hidden=&sortColOrder_hidden=&final_cols=ID%7CPRO_NAME_TXT%7CPRO_DEF_TXT%7CCATEGORY%7CPARENT&hidden_id=&searchstr=ALLFLDS%3A%22VAR+%22
2. Click on VAR ID link, try the first one VAR_006204
3. See error: goes to http://web.expasy.org/%3Cfont%20color=red%3Evar%3C/font%3Eiant_pages/VAR_*006204.html

**Expected behavior**
The link should go here: https://web.expasy.org/variant_pages/VAR_006204.html

**Browser**
Firefox, Chrome

**Comment by nataled** [comment]
This is actually due to rendering the search result such that the search term is highlighted. In this case the searched item is partial (so that, for example, if you searched instead for VAR_006204, the link would work correctly. Should be a fairly easy fix. Will need to separate the displayed item and its link in processing.

@hongzhanhuang

**Comment by carighi** [comment]
By the way, the VAR ID in the xref of the entry report has no link 


Ceci 

----- Original Message -----

**Comment by nataled** [comment]
I was just in the process of writing that ticket :)

**Comment by hongzhanhuang** [comment]
Jian had fixed the problem for VAR_ID links in the text search page.
