### ISSUE TITLE
Missing hyperlinks to UniProtKB_VAR in PRO entry pages

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#149]
**Describe the issue**
Follow-up from #148. The entry pages fail to have the VAR_ hyperlinked

**To Reproduce**
1. Go to https://proconsortium.org/app/entry/PR%3A000000328/
2. Scroll down to 'Related Cross References'
3. The text 'UniProtKB_VAR:VAR_006204' is not hyperlinked.

**Expected behavior**
UniProtKB_VAR:VAR_006204 should be linked to https://web.expasy.org/variant_pages/VAR_006204.html

**Browser**
Firefox, Edge

@hongzhanhuang

**Comment by Julie-Cowart** [comment]
Fixed on test site. See https://proconsortium.org/app_test/entry/PR%3A000000328/

**Comment by Julie-Cowart** [comment]
in production
