### ISSUE TITLE
"Test Site" showing on external page

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#151]
**Describe the issue**
The banner for the "Properties defined in PRO" page (accessible from the SPARQL page) still shows "Test Site"

**To Reproduce**
1. Go to https://proconsortium.org/pro_doc.shtml
2. Note the header

**Expected behavior**
Shouldn't be labeled as such.

**Comment by hongzhanhuang** [comment]
Will fix it.

**Comment by chumingc** [comment]
Fixed.

Chuming
