### ISSUE TITLE
Broken links in PRO browser

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#155]
**Describe the issue**
The links to individual PRO terms from within the browser are old.

**To Reproduce**
1. Go to the PRO home page.
2. Click on 'Browse' in the header
    -> goes to https://proconsortium.org/pro_browse.shtml
3. Click on any of the links to individual terms.
4. These attempt to go to research.bioinformatics.udel.edu

**Expected behavior**
The links should go to https://proconsortium.org/app/entry/

**Comment by hongzhanhuang** [comment]
Jian has fixed the problem.
