### ISSUE TITLE
S. pombe rad9 residue corrections PR:000049981 & PR:000049982

### ISSUE THREAD

**Issue by mah11** [PROconsortium/PRoteinOntology#156]
I have just noticed that two PRO entries for phosphorylated forms of S. pombe Rad9 mention Ser-412, but Rad9 residue 412 is Thr. (The error was probably originally mine, since I requested them.)

In both PR:000049981 and PR:000049982 Ser-412 should be corrected to Thr-412. Apologies for getting it wrong back then and for inconvenience now.

The corrected OBO stanzas would be:

[Term]
id: PR:000049981
name: DNA repair protein rad9 phosphorylated 2 (Schizosaccharomyces pombe)
def: "A DNA repair protein rad9 (Schizosaccharomyces pombe) that has been phosphorylated on a residue equivalent to Thr-412 of the amino acid sequence represented by UniProtKB:P26306. Example: UniProtKB:P26306, Thr-412, MOD:00046." [PRO:CNA, PomBase:MAH, PMID:21561865]
comment: Category=organism-modification. Requested by=PomBase. Evidence=(ECO:0000006, based on PMID:21561865). Kinase=("rad3"; PR:Q02099; Thr-412). Kinase=("tel1"; PR:O74630; Thr-412).
is_a: PR:000044575 ! DNA repair protein rad9 (Schizosaccharomyces pombe)

[Term]
id: PR:000049982
name: DNA repair protein rad9 phosphorylated 3 (Schizosaccharomyces pombe)
def: "A DNA repair protein rad9 (Schizosaccharomyces pombe) that has been phosphorylated on residues equivalent to Thr-412 and Ser-423 of the amino acid sequence represented by UniProtKB:P26306. Example: UniProtKB:P26306, Thr-412/Ser-423, MOD:00046." [PRO:CNA, PomBase:MAH, PMID:21561865]
comment: Category=organism-modification. Requested by=PomBase. Evidence=(ECO:0000006, based on PMID:21561865). Kinase=("rad3"; PR:Q02099; Ser-423).
is_a: PR:000044575 ! DNA repair protein rad9 (Schizosaccharomyces pombe)

**Comment by nataled** [comment]
Never fear! We actually just did a check of all sites a few weeks ago, and I caught them already. The corrections will be public with the next release (in progress).
