### ISSUE TITLE
Supply GZIP version to alleviate network limitations

### ISSUE THREAD

**Issue by matentzn** [PROconsortium/PRoteinOntology#158]
Hey all,

would you mind supplying a gzip version of pr as part of your normal pipeline [here](ftp://ftp.proconsortium.org/databases/ontology/pro_obo/) and make sure we have a valid purl to access it? This will help us reducing the network load when dealing with PR in our release pipelines.

Chebi, for example, offers a purl like that: http://purl.obolibrary.org/obo/chebi.owl.gz

but this would be fine as well: http://purl.obolibrary.org/obo/pr/pr.owl.gz

Let me know if you need help with the PURL config!

Thanks a lot!
Nico

**Comment by nataled** [comment]
Hi Nico,

A timely request, as we are about to put out another release. Yes, we can do that.

@hongzhanhuang please include in the release pipeline the creation of pro_reasoned.owl.gz, to which I'll point the PURL.

**Comment by nataled** [comment]
The new release is now available, along with the ability to download a compressed version using the following PURL:

 http://purl.obolibrary.org/obo/pr.owl.gz

**Comment by matentzn** [comment]
Thanks!

**Comment by matentzn** [comment]
The purl is failing now again: There is no gz file in https://proconsortium.org/download/current/

**Comment by hongzhanhuang** [comment]
fixed.

**Comment by matentzn** [comment]
Thank you! Will this now update automatically in the future? When you do the next release?

**Comment by nataled** [comment]
Yes, we will incorporate the production of such a file with each new release. Sorry for the breakdown; somehow these things happen when you introduce a new element to a long-standing pipeline!
