### ISSUE TITLE
Broken links when searching for 'app' in PRO

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#166]
**Describe the issue**
When searching for a particular string in PRO, the results are highlighted with red text. However, when that string happens to also be part of the URL, the URL itself will end up having the highlight incorporated into it, rendering the link broken. I initially found this while looking at the set of Alzheimer-related proteins encoded by the APP gene. 

**To Reproduce**
1. Go to http://proconsortium.org
2. In the box labeled "Search PRO (enter text or ID)" enter 'app' ('entry' works also) and perform the search. 
3. Click any PRO term in the first column.
4. You'll get a 'not found' error. Interestingly, the report when using 'app' differs from the report when using 'entry'.

**Expected behavior**
It is clear that the problem is created because the HTML code for highlighting the string match was applied to the URL. It should not be.

**Comment by hongzhanhuang** [comment]
Jian has fixed the problem.
