### ISSUE TITLE
Revise error message when search term not found

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#170]
**Describe the issue**
When searching the PRO website, if nothing is found, there is an error message, but the message needs to be revised.

**To Reproduce**
1. Go to https://proconsortium.org/pro.shtml
2. Enter BBBBBBB in the search box at the right of the page and run the search
3. The returned message is:

	No found. ..

	Please try again.

The grammar and punctuation should be revised as indicated below.

**Expected behavior**

The corrected message should be:

	Not found...

	Please try again.

That is, 'No' should be 'Not' and the space between the dots should be removed.

**Comment by jz26** [comment]
corrected.
