### ISSUE TITLE
Search result table - incorrect heading label

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#171]
**Describe the issue**
One of the columns for the search result table is mislabeled.

**To Reproduce**
1. From the PRO home page, do any search.
2. The first column shows "NOREDPRO ID"

**Expected behavior**
The heading should be "PRO ID"

**Screenshots**

![PRO column heading issue](https://user-images.githubusercontent.com/13770634/74245516-1f85b480-4cb1-11ea-8156-7c4eb41a28d5.jpg)

**Comment by jz26** [comment]
fixed.
