### ISSUE TITLE
Need to change link for term requests

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#172]
**Describe the issue**
On the dynamic term generator page, we point to the old term request page.

**To Reproduce**
1. Go to the home page
2. In the "Retrieve a PRO entry (enter a PRO ID)" box, enter "P12345" and click the arrow.
3. The resulting page will show dynamic term generator results. Mousing over 'requested' will show the old URL (to sourceforge), which is https://sourceforge.net/p/pro-obo/term-requests/new/

**Expected behavior**
The new link should point to the PURL for term requests, which is http://purl.obolibrary.org/obo/pr/tracker

**Comment by jz26** [comment]
changed

**Comment by jz26** [comment]
Strange to me:
why the new link is redirected to:
https://github.com/PROconsortium/PRoteinOntology/issues
?

**Comment by nataled** [comment]
That is the PRO tracker. I'm thinking we should make it go directly to term request. Will get back to you soon.

**Comment by nataled** [comment]
I think we're going to need a better solution, but for now use this URL:

https://github.com/PROconsortium/PRoteinOntology/issues/new?assignees=karenross&labels=Term+Request&template=1--term-request.md&title=Dynamic+term+request%3A+

Question: would it be possible to add the requested term to the URL? That is, if the person requests P12345, the URL would be:

https://github.com/PROconsortium/PRoteinOntology/issues/new?assignees=karenross&labels=Term+Request&template=1--term-request.md&title=Dynamic+term+request%3A+P12345

**Comment by jz26** [comment]
adding a term is possible.

**Comment by nataled** [comment]
Yep, thanks! Do you think we should add a note to the dynamic term result saying that a github account is required?

**Comment by nataled** [comment]
Perhaps change "Please note that this term was generated dynamically and will not appear in any downloadable version of PRO unless such is requested." to "This term was generated dynamically and will not appear in any downloadable version of PRO unless such is requested. Please note that a github login is required."

(with of course the word 'requested' linked as before)

**Comment by jz26** [comment]
pre-view is ready.

**Comment by nataled** [comment]
Looks good, though when I said 'requested linked as before' I meant as we just decided. That is, it should still be linked (but to the github URL we worked out, with the accession etc)

**Comment by jz26** [comment]
pre-view is ready.

**Comment by nataled** [comment]
Perfect. Thanks!

But now I just noticed another related issue. Using a different accession, such as P12347, the user gets a different message "This service is unable to process this particular term. Please inform the PRO developers." The message is fine, but we should again provide a link. In this case, the link should be placed on the words "inform the PRO developers" and the link should be to 

https://github.com/PROconsortium/PRoteinOntology/issues/new?assignees=nataled&labels=Term+Request&template=1--term-request.md&title=Dynamic term+failed%3A+

again with the accession at the end.

The error message should be "This service is unable to process this particular term. Please inform the PRO developers. Please note that a github login is required."

**Comment by nataled** [comment]
Oops. Please add a '+' between 'Dynamic' and 'term' (in place of the space):

https://github.com/PROconsortium/PRoteinOntology/issues/new?assignees=nataled&labels=Term+Request&template=1--term-request.md&title=Dynamic+term+failed%3A+

Sorry.

**Comment by jz26** [comment]
There are third case too: such as P123457. Is that also an issue?

**Comment by nataled** [comment]
No, that one is fine.

**Comment by jz26** [comment]
Also, for the 2nd case, the error message is hard coded by your program:

----------------------------------------------------------------
[www@pir1 on-the-fly]$ cd /home/nataled/on-the-fly/
[www@pir1 on-the-fly]$ grep This  PRO_flat2stanza.pl
# This script will grab the flat-format version of the appropriate entry
   print "This service is unable to process this particular term. Please inform the PRO developers.\n";_
---------------------------------------------------------------

It is ideal to deal with it from it's source by you. If otherwise you prefer me to manipulate your text from my end, I would like to add this "(click here)" in quotations to you text to make it easier.

Let me know, thanks.

**Comment by nataled** [comment]
I will handle it from my end. Thanks! 

I will leave this issue open until I fix it, but I'm assigning it to me. Thanks for your help!
