### ISSUE TITLE
Term issue: pombe GTP-bound rho2

### ISSUE THREAD

**Issue by mah11** [PROconsortium/PRoteinOntology#174]
I've modeled the suggestion on a combination of PR:Q10133 and PR:000044799:

id: PR:new
name: GTP-binding protein rho2,  GTP-bound form (Schizosaccharomyces pombe 972h-)
def: "A GTP-binding protein rho2 (Schizosaccharomyces pombe 972h-) that is non-covalently bound to GTP." [PRO:??, PomBase:MH, PMID:26960792]
comment: Category=organism-complex. Requested by=PomBase.
synonym: "Spom972h-rho2/GTP+" EXACT PRO-short-label [PRO:??]

Let me know if you need anything else. Thanks!

**Comment by nataled** [comment]
Just to verify: You want the term for the specific strain? I ask because usually PomBase requests are for the species rather than strain.

**Comment by mah11** [comment]
Hmm, good point. I did just copy & paste from the rho2 entry I found, but a term for the species would actually be more useful. Well spotted!

**Comment by nataled** [comment]
Yours is the second term. Thanks for using PRO!

[Term]
id: PR:000050250
name: GTP-binding protein rho2 (Schizosaccharomyces pombe)
def: "A Rho-related small GTPase that is a translation product of the rho2 gene in Schizosaccharomyces pombe." [PRO:DAN, UniProtKB:Q10133]
comment: Category=organism-gene. Requested by=PomBase.
synonym: "Spom-rho2" EXACT PRO-short-label [PRO:DAN]
synonym: "rho2" RELATED Gene-based []
synonym: "SPAC16.01" RELATED Gene-based []
intersection_of: PR:000000122 ! Rho-related small GTPase
intersection_of: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
intersection_of: has_gene_template PomBase:SPAC16.01 ! rho2 (Schizosaccharomyces pombe)

[Term]
id: PR:000050251
name: GTP-binding protein rho2, GTP-bound form (Schizosaccharomyces pombe)
def: "A GTP-binding protein rho2 (Schizosaccharomyces pombe) that is non-covalently bound to GTP." [PRO:DAN, PomBase:MAH, PMID:26960792]
comment: Category=organism-complex. Requested by=PomBase.
synonym: "Spom-rho2/GTP+" EXACT PRO-short-label [PRO:DAN]
intersection_of: PR:000050250 ! GTP-binding protein rho2 (Schizosaccharomyces pombe)
intersection_of: non-covalently_bound_to CHEBI:15996 ! GTP
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by mah11** [comment]
It's a pleasure - you guys are always so prompt & helpful :)
