### ISSUE TITLE
Term issue: immunoglobulin heavy constant terms requests

### ISSUE THREAD

**Issue by rvita** [PROconsortium/PRoteinOntology#175]
We are requesting the following new terms:
immunoglobulin   heavy constant gamma (can this be the parent of immunoglobulin heavy constant gamma 1, 2, 3, and 4? Will that work?)
immunoglobulin   heavy constant gamma 2a (IGG2a)
immunoglobulin   heavy constant gamma 2b (IGG2b)
immunoglobulin   heavy constant gamma 2c (IGG2c)
--
Thanks

--

--

--

**Comment by nataled** [comment]
Hi Randi,
Are these terms being requested as species non-specific terms, or did you want the species specific ones? If the latter, which species? Human for IGG2, and mouse for IGG2a, 2b, and 2c? Are you interested in the IgG antibody terms too?

**Comment by rvita** [comment]
Only species non-specific terms are needed. If we decide that we need species specific terms later, we will create a new ticket and will include additional isotypes. Thanks!

**Comment by nataled** [comment]
One more question. The terms you requested amount to just parts of proteins--not even a full heavy chain. Is this intended? These seem different from what we discussed over email, so I just wanted to be sure.

**Comment by rvita** [comment]
Darren is correct, I want to amend my request to be:
IgG heavy chain protein (species non-specific) (can this be the parent of immunoglobulin heavy gamma 1, 2, 3, and 4? Will that work?)
IgG2a heavy chain protein (IGG2a)
IgG2b heavy chain protein 2b (IGG2b)
IgG2c heavy chain protein 2c (IGG2c)
and add:
IgM heavy chain protein
IgD heavy chain protein
IgE heavy chain protein
IgG1 heavy chain protein
IgG2 heavy chain protein
IgG3 heavy chain protein
IgG4 heavy chain protein
-

**Comment by nataled** [comment]
Hi Randi,
Terms are finished, as outlined below. Quick question: Were these created on behalf of HIPC? Or a different organization?

Hierarchy (listed for completeness)

<pre>
immunoglobulin heavy chain protein  (EXISTING PR:000050174)
  IgA heavy chain protein           (EXISTING PR:000050176)
    IgA1 heavy chain protein        (EXISTING PR:000050177)
    IgA2 heavy chain protein        (EXISTING PR:000050178)
  IgD heavy chain protein           (req-EXISTING PR:000050186)
  IgG heavy chain protein           (req-NEW PR:000050252)
    IgG1 heavy chain protein        (req-NEW PR:000050253)
    IgG2 heavy chain protein        (req-NEW PR:000050254)
    IgG3 heavy chain protein        (req-NEW PR:000050255)
    IgG4 heavy chain protein        (req-NEW PR:000050256)
    IgG2a heavy chain protein       (req-NEW PR:000050259)
    IgG2b heavy chain protein       (req-NEW PR:000050260)
    IgG2c heavy chain protein       (req-NEW PR:000050261)
  IgM heavy chain protein           (req-NEW PR:000050257)
  IgE heavy chain protein           (req-NEW PR:000050258)
</pre>

I also added some synonyms to existing heavy chain terms to aid finding them. The new terms, given below, are available for reference immediately (that is, the PURLs will resolve). However, they will only be downloadable from the in-progress subset of PRO (http://purl.obolibrary.org/obo/pr/pr-dev.obo) until the next release.

<pre>
[Term]
id: PR:000050252
name: IgG heavy chain protein
def: "An immunoglobulin heavy chain protein in which the constant region is encoded by some IgG gene segment." [PRO:DAN]
comment: Category=family. Note: In human, IgG constant gene segments are IgG1, IgG2, IgG3, and IgG4.
synonym: "IgHG" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin G heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin gamma heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain gamma" EXACT [PRO:DAN]
is_a: PR:000050174 ! immunoglobulin heavy chain protein

[Term]
id: PR:000050253
name: IgG1 heavy chain protein
def: "An IgG heavy chain protein in which the constant region is encoded by the IgG1 gene segment." [PRO:DAN]
comment: Category=gene.
synonym: "IgHG1" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin G1 heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin gamma 1 heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain gamma 1" EXACT [PRO:DAN]
is_a: PR:000050252 ! IgG heavy chain protein

[Term]
id: PR:000050254
name: IgG2 heavy chain protein
def: "An IgG heavy chain protein in which the constant region is encoded by the IgG2 gene segment." [PRO:DAN]
comment: Category=gene.
synonym: "IgHG2" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin G2 heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin gamma 2 heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain gamma 2" EXACT [PRO:DAN]
is_a: PR:000050252 ! IgG heavy chain protein

[Term]
id: PR:000050255
name: IgG3 heavy chain protein
def: "An IgG heavy chain protein in which the constant region is encoded by the IgG3 gene segment." [PRO:DAN]
comment: Category=gene.
synonym: "IgHG3" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin G3 heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin gamma 3 heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain gamma 3" EXACT [PRO:DAN]
is_a: PR:000050252 ! IgG heavy chain protein

[Term]
id: PR:000050256
name: IgG4 heavy chain protein
def: "An IgG heavy chain protein in which the constant region is encoded by the IgG4 gene segment." [PRO:DAN]
comment: Category=gene.
synonym: "IgHG4" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin G4 heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin gamma 4 heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain gamma 4" EXACT [PRO:DAN]
is_a: PR:000050252 ! IgG heavy chain protein

[Term]
id: PR:000050257
name: IgM heavy chain protein
def: "An immunoglobulin heavy chain protein in which the constant region is encoded by the IgM gene segment." [PRO:DAN]
comment: Category=gene.
synonym: "IgHM" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin M heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin mu heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain mu" EXACT [PRO:DAN]
is_a: PR:000050174 ! immunoglobulin heavy chain protein

[Term]
id: PR:000050258
name: IgE heavy chain protein
def: "An immunoglobulin heavy chain protein in which the constant region is encoded by the IgE gene segment." [PRO:DAN]
comment: Category=gene.
synonym: "IgHE" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin E heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin epsilon heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain epsilon EXACT [PRO:DAN]
is_a: PR:000050174 ! immunoglobulin heavy chain protein

[Term]
id: PR:000050259
name: IgG2a heavy chain protein
def: "An IgG heavy chain protein in which the constant region is encoded by the IgG2a gene segment." [PRO:DAN]
comment: Category=gene.
synonym: "IgHG2a" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin G2a heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin gamma 2a heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain gamma 2a" EXACT [PRO:DAN]
is_a: PR:000050252 ! IgG heavy chain protein

[Term]
id: PR:000050260
name: IgG2b heavy chain protein
def: "An IgG heavy chain protein in which the constant region is encoded by the IgG2b gene segment." [PRO:DAN]
comment: Category=gene.
synonym: "IgHG2b" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin G2b heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin gamma 2b heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain gamma 2b" EXACT [PRO:DAN]
is_a: PR:000050252 ! IgG heavy chain protein

[Term]
id: PR:000050261
name: IgG2c heavy chain protein
def: "An IgG heavy chain protein in which the constant region is encoded by the IgG2c gene segment." [PRO:DAN]
comment: Category=gene.
synonym: "IgHG2c" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin G2c heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin gamma 2c heavy chain" EXACT [PRO:DAN]
synonym: "immunoglobulin heavy chain gamma 2c" EXACT [PRO:DAN]
is_a: PR:000050252 ! IgG heavy chain protein

</pre>

**Comment by rvita** [comment]
Thanks so much, that was amazingly fast! Please attribute the term requests to IEDB.

**Comment by nataled** [comment]
Will do, thanks!
