### ISSUE TITLE
TMEM133 (human) points to obsolete HGNC identifier

### ISSUE THREAD

**Issue by callahantiff** [PROconsortium/PRoteinOntology#176]
**PRO Term:** [TMEM133 (human)](http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=24033) 

**Bug description:**   
-  PRO term currently points to [HGNC:24033](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/24033), which has been withdrawn by the organization
- HGNC proposed a new identifier for this gene ([HGNC:26545](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:26545))

**Comment by nataled** [comment]
Thank you for the alert! As it turns out, the PRO term referencing that HGNC entry (PR:Q9H2Q1) is slated to be deprecated anyway. PRO already has a replacement term that references the new gene ARHGAP42 (PR:A6NI28).

**Comment by callahantiff** [comment]
@nataled - Thank you for looking into this and for the update!
