### ISSUE TITLE
PRO wiki links need updating

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#177]
**Describe the issue**
On the home page there are two links to the PRO wiki. Each of these currently points to pir17. Please revise to:

https://confluence.proteininformationresource.org/display/PROWIKI

**Comment by jz26** [comment]
revised by Les

**Comment by nataled** [comment]
You are right that I needed to use a new browser to see it. I originally was using Firefox when I reported the issue. After the fix, I tried Firefox again. The problem still remained, even after refreshing multiple times (the mouse-over the link shows pir17, clicking the link takes me to https://confluence.proteininformationresource.org/#all-updates just as it did before). Using Edge, even though mouse-over still shows pir17, the destination is the correct one (that is, it goes to https://confluence.proteininformationresource.org/display/PROWIKI/Home).

I can't figure out why mouse-over shows the old link, and why it won't work in Firefox. By the way, when I say "mouse-over" I mean that the browser shows the actual link, as shown in the attached picture. So it looks like the change made was to a redirect? All that was needed was a URL change, no? It seems that the URL was kept as-is. If that's correct, please just change it.
![Untitled](https://user-images.githubusercontent.com/13770634/78139568-bb50b880-73f6-11ea-8996-98194d181e81.png)

**Comment by jz26** [comment]
After back and forth discussions, a decision is made:

all the wiki links on PRO webpages will point to
http://purl.obolibrary.org/obo/pr/wiki.

Cheers.

-jz
