### ISSUE TITLE
Improve 'not found' search result

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#178]
**Describe the issue**
When searching for a PRO term using a specific identifier that was not part of a full release, there is a simple message that says "Not found. Please try again." Enough people do this kind of search after requesting terms--which will always fail--that we should suggest that they do a retrieval instead.

NOTE: once a PRO update is done, this will not be testable again until a new pro_wv is produced.

**To Reproduce**
1. Enter "PR:Q99PW8-1" in the right-most "Search PRO..." box to perform the search. The search will (properly) fail with the following message:

	Not found.
	Please try again.

**Hoped for behavior**
Three possibilities, listed in order of ease of implementation (of course, the most difficult one is also the most preferred):

1) Return the same message, but add a suggestion:

	Not found.
	Please try again.
	If you are searching with a specific PRO identifier, please try the 'Retrieve' box instead.

2) Return the same message, but add the suggestion ONLY if a PRO or UniProtKB identifier was used as the search term. If this is implemented, the error message should be:

	Not found.
	Please try the 'Retrieve' box instead.

3) If a term is not found, and the search string conforms to a PRO or UniProtKB identifier, switch to a retrieval-type search automatically to return the result. If there is STILL no result, just let the Retrieve error ("Please provide a valid ID") show.

**Comment by hongzhanhuang** [comment]
Jian had fixed the problem with option 3.
