### ISSUE TITLE
New PRO terms for human IgG immunologlobulin complexes

### ISSUE THREAD

**Issue by addiehl** [PROconsortium/PRoteinOntology#179]
New terms for human IgG immunologlobulin complexes (part of the HIPC-CL collaboration)

These are pretty straight forward, similar to existing terms for IgA and IgD, except I have added a bit of complexity to better reflect biological reality.  Immunoglobulin heavy chains actually occur as two major isoforms for each isotype, a secretory form lacking a transmembrane segment that is encoded by the 2 3' exons of each constant region gene, and a membrane-bound form containing the two 3' exons.  A somewhat atypically alternative splicing mechanism involving a regulated use of polyadenylation site that sits 5' of the 2 3' exons controls whether the short secretory form mRNA is produced or the full-length transmembrane form is produced.

Thus, I have included heavy chain isoforms for both the secretory form and the transmembrane form.  Note that I make use of recently created non-species specific form of the IgG1, IgG2, IgG3, and IgG4 heavy chain PRO IDs created in response to #175.  Appropriate papers are referenced for all definitions, in case you find this bit of molecular biology as fascinating as I did. Note that I want to go back and revise the IgA and IgD terms to match this more complex representation as well.

Note also there is another cute biological/ontological twist pertaining to human IgG4.  Human soluble (non-membrane bound) IgG4, unlike other immunoglobulins, has a high rate of exchange of so-called "half-molecule arms" where a half-molecule arm consists of one heavy chain and one light chain.  This results in the formation of bivalent complexes with two independent binding sites that are functionally molevalent in most biological situations, meaning they do not crosslink antigens effectively nor form immune complexes.  This detail require a tweak in the definition to say simply that an Ig4 immunoglobulin complex is "composed of two immunoglobulin heavy chains of an IgG4 isotype and two immunoglobulin light chains," rather than "composed of two identical immunoglobulin heavy chains of an IgG4 isotype and two identical immunoglobulin light chains."  One might wonder is this revised definition represents a true-path violation with the parent GO term for 'IgG immunoglobulin complex' which indeed specifies the word identical for the heavy and light chains.

There are two ways to resolve this:
1) ignore this issue and probably nobody cares since the GO term has no logical definition to mess up reasoning.
2) soften the GO term text definition to either remove the word identical (option 2A) or add the phrase in its canonical form (used in the parent GO:0019814 immunoglobulin complex definition as a hedge)(option 2B).

I favor option 2A.

Keep in mind the membrane-bound form (B cell receptor form) of human IgG4 does have two identical heavy and two identical light chains since it is imbedded in the clonotypic B cell where it is synthesized.

Further term requests pertaining to human IgM and human IgE are forthcoming as well.

Also, thanks for your tolerance all copy-paste errors/typos that I have failed to catch.  Feel free to adjust the PRO-short-labels as desired and add or take away cardinality constraints.

Thanks,
Alex

[Term]
id: PR:NewTerm1
name: IgG1 immunoglobulin complex (human)
def: "A protein complex composed of two identical immunoglobulin heavy chains of an IgG1 isotype and two identical immunoglobulin light chains, held together by disulfide bonds. An IgG1 immunoglobulin complex may be embedded in the plasma membrane or present in the extracellular space, in mucosal areas or other tissues, or circulating in the blood or lymph." [GOC:add, PMID:25368619]
comment: Note that an IgG1 immunoglobulin complex has the function of antigen binding if a suitable antigen is available.
synonym: "hIgG1" EXACT PRO-short-label [PRO:add]
synonym: "IgG1, human" EXACT [GOC:add]
synonym: "IgG, human" BROAD [GOC:add]
synonym: "IgG1 antibody, human" NARROW [GOC:add]
is_a: GO:0071735 ! IgG immunoglobulin complex
relationship: has_component PR:NewTerm5 ! IgG1 heavy chain protein (human)
relationship: has_component PR:000050183 ! immunoglobulin light chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm2
name: IgG2 immunoglobulin complex (human)
def: "A protein complex composed of two identical immunoglobulin heavy chains of an IgG2 isotype and two identical immunoglobulin light chains, held together by disulfide bonds. An IgG2 immunoglobulin complex may be embedded in the plasma membrane or present in the extracellular space, in mucosal areas or other tissues, or circulating in the blood or lymph." [GOC:add, PMID:25368619]
comment: Note that an IgG2 immunoglobulin complex has the function of antigen binding if a suitable antigen is available.
synonym: "hIgG2" EXACT PRO-short-label [PRO:add]
synonym: "IgG2, human" EXACT [GOC:add]
synonym: "IgG, human" BROAD [GOC:add]
synonym: "IgG2 antibody, human" NARROW [GOC:add]
is_a: GO:0071735 ! IgG immunoglobulin complex
relationship: has_component PR:NewTerm6 ! IgG2 heavy chain protein (human)
relationship: has_component PR:000050183 ! immunoglobulin light chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm3
name: IgG3 immunoglobulin complex (human)
def: "A protein complex composed of two identical immunoglobulin heavy chains of an IgG3 isotype and two identical immunoglobulin light chains, held together by disulfide bonds. An IgG3 immunoglobulin complex may be embedded in the plasma membrane or present in the extracellular space, in mucosal areas or other tissues, or circulating in the blood or lymph." [GOC:add, PMID:25368619]
comment: Note that an IgG3 immunoglobulin complex has the function of antigen binding if a suitable antigen is available.
synonym: "hIgG3" EXACT PRO-short-label [PRO:add]
synonym: "IgG3, human" EXACT [GOC:add]
synonym: "IgG, human" BROAD [GOC:add]
synonym: "IgG3 antibody, human" NARROW [GOC:add]
is_a: GO:0071735 ! IgG immunoglobulin complex
relationship: has_component PR:NewTerm6 ! IgG3 heavy chain protein (human)
relationship: has_component PR:000050183 ! immunoglobulin light chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm4
name: IgG4 immunoglobulin complex (human)
def: "A protein complex composed of two immunoglobulin heavy chains of an IgG4 isotype and two immunoglobulin light chains, held together by disulfide bonds. An IgG4 immunoglobulin complex may be embedded in the plasma membrane or present in the extracellular space, in mucosal areas or other tissues, or circulating in the blood or lymph. Note that secreted IgG4 often undergoes half-molecule exchange (exchange of one heavy chain-light chain arm for another) to form bivalent complexes (two independent binding sites) that are functionally molevalent in most biological situations." [GOC:add, PMID:25368619, PMID:19222496]
comment: Note that an IgG4 immunoglobulin complex has the function of antigen binding if a suitable antigen is available.
synonym: "hIgG4" EXACT PRO-short-label [PRO:add]
synonym: "IgG4, human" EXACT [GOC:add]
synonym: "IgG, human" BROAD [GOC:add]
synonym: "IgG4 antibody, human" NARROW [GOC:add]
is_a: GO:0071735 ! IgG immunoglobulin complex
relationship: has_component PR:NewTerm6 ! IgG4 heavy chain protein (human)
relationship: has_component PR:000050183 ! immunoglobulin light chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm5
name: IgG1 heavy chain protein (human)
def: "An IgG heavy chain protein in which the constant region is encoded by the human IgG1 gene segment." [GOC:add]
synonym: "IGHG1 (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G1 heavy chain (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 1 heavy chain (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 1 (human)" EXACT [GOC:add]
is_a: PR:000050253 ! IgG1 heavy chain protein
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm6
name: IgG2 heavy chain protein (human)
def: "An IgG heavy chain protein in which the constant region is encoded by the human IgG2 gene segment." [GOC:add]
synonym: "IGHG2 (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G2 heavy chain (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 2 heavy chain (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 2 (human)" EXACT [GOC:add]
is_a: PR:000050254 ! IgG2 heavy chain protein
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm7
name: IgG3 heavy chain protein (human)
def: "An IgG heavy chain protein in which the constant region is encoded by the human IgG3 gene segment." [GOC:add]
synonym: "IGHG3 (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G3 heavy chain (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 3 heavy chain (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 3 (human)" EXACT [GOC:add]
is_a: PR:000050255 ! IgG3 heavy chain protein
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm8
name: IgG4 heavy chain protein (human)
def: "An IgG heavy chain protein in which the constant region is encoded by the human IgG4 gene segment." [GOC:add]
synonym: "IGHG4 (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G4 heavy chain (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 4 heavy chain (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 4 (human)" EXACT [GOC:add]
is_a: PR:000050256 ! IgG4 heavy chain protein
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm9
name: IgG1 heavy chain protein, secretory isoform (human)
def: "A human IgG1 heavy chain protein of the secretory isoform whose mRNA is polyadenylated at a site 5' to the membrane exons preventing their incorporation the final spliced mRNA." [GOC:add, PMID:9185563, PMID:17496345]
synonym: "IGHG1, secretory isoform  (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G1 heavy chain, secretory isoform  (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 1 heavy chain, secretory isoform  (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 1, secretory isoform  (human)" EXACT [GOC:add]
is_a: PR:NewTerm5 ! IgG1 heavy chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm10
name: IgG2 heavy chain protein, secretory isoform (human)
def: "A human IgG2 heavy chain protein of the secretory isoform whose mRNA is polyadenylated at a site 5' to the membrane exons preventing their incorporation the final spliced mRNA." [GOC:add, PMID:9185563, PMID:17496345]
synonym: "IGHG2, secretory isoform (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G2 heavy chain, secretory isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 2 heavy chain, secretory isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 2, secretory isoform (human)" EXACT [GOC:add]
is_a: PR:NewTerm6 ! IgG2 heavy chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm11
name: IgG3 heavy chain protein, secretory isoform (human)
def: "A human IgG3 heavy chain protein of the secretory isoform whose mRNA is polyadenylated at a site 5' to the membrane exons preventing their incorporation the final spliced mRNA." [GOC:add, PMID:9185563, PMID:17496345]
synonym: "IGHG3, secretory isoform (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G3 heavy chain, secretory isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 3 heavy chain, secretory isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 3, secretory isoform (human)" EXACT [GOC:add]
is_a: PR:NewTerm7 ! IgG3 heavy chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm12
name: IgG4 heavy chain protein, secretory isoform (human)
def: "A human IgG4 heavy chain protein of the secretory isoform whose mRNA is polyadenylated at a site 5' to the membrane exons preventing their incorporation the final spliced mRNA." [GOC:add, PMID:9185563, PMID:17496345]
synonym: "IGHG4, secretory isoform (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G4 heavy chain, secretory isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 4 heavy chain, secretory isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 4, secretory isoform (human)" EXACT [GOC:add]
is_a: PR:NewTerm8 ! IgG4 heavy chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm13
name: IgG1 heavy chain protein, membrane-bound isoform (human)
def: "A human IgG1 heavy chain protein of the membrane-bound isoform whose mRNA incorporates the 3' membrane exons in the final spliced mRNA." [GOC:add, PMID:9185563, PMID:17496345]
synonym: "IGHG1, membrane-bound isoform  (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G1 heavy chain, membrane-bound isoform  (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 1 heavy chain, membrane-bound isoform  (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 1, membrane-bound isoform  (human)" EXACT [GOC:add]
is_a: PR:NewTerm5 ! IgG1 heavy chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm14
name: IgG2 heavy chain protein, membrane-bound isoform (human)
def: "A human IgG2 heavy chain protein of the membrane-bound isoform whose mRNA incorporates the 3' membrane exons in the final spliced mRNA." [GOC:add, PMID:9185563, PMID:17496345]
synonym: "IGHG2, membrane-bound isoform (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G2 heavy chain, membrane-bound isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 2 heavy chain, membrane-bound isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 2, membrane-bound isoform (human)" EXACT [GOC:add]
is_a: PR:NewTerm6 ! IgG2 heavy chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm15
name: IgG3 heavy chain protein, membrane-bound isoform (human)
def: "A human IgG3 heavy chain protein of the membrane-bound isoform whose mRNA incorporates the 3' membrane exons in the final spliced mRNA." [GOC:add, PMID:9185563, PMID:17496345]
synonym: "IGHG3, membrane-bound isoform (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G3 heavy chain, membrane-bound isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 3 heavy chain, membrane-bound isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 3, membrane-bound isoform (human)" EXACT [GOC:add]
is_a: PR:NewTerm7 ! IgG3 heavy chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm16
name: IgG4 heavy chain protein, membrane-bound isoform (human)
def: "A human IgG4 heavy chain protein of the membrane-bound isoform whose mRNA incorporates the 3' membrane exons in the final spliced mRNA." [GOC:add, PMID:9185563, PMID:17496345]
synonym: "IGHG4, membrane-bound isoform (human)" EXACT PRO-short-label [GOC:add]
synonym: "immunoglobulin G4 heavy chain, membrane-bound isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin gamma 4 heavy chain, membrane-bound isoform (human)" EXACT [GOC:add]
synonym: "immunoglobulin heavy chain gamma 4, membrane-bound isoform (human)" EXACT [GOC:add]
is_a: PR:NewTerm8 ! IgG4 heavy chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm17
name: IgG1 immunoglobulin complex, circulating (human)
def: "A protein complex composed of two identical immunoglobulin heavy chains of an IgG1 isotype of the secretory isoform and two identical immunoglobulin light chains, held together by disulfide bonds and present in the extracellular space, in mucosal areas or other tissues, or circulating in the blood or lymph." [GOC:add, PMID:25368619]
synonym: "hIgG1/circulating" EXACT PRO-short-label [PRO:add]
synonym: "IgG1 antibody, human" EXACT [GOC:add]
synonym: "IgG antibody, human" BROAD [GOC:add]
is_a: PR:NewTerm1 ! IgG1 immunoglobulin complex (human)
relationship: has_component PR:NewTerm9 ! IgG1 heavy chain protein, secretory isoform (human)
relationship: has_component PR:000050183 ! immunoglobulin light chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm18
name: IgG2 immunoglobulin complex, circulating (human)
def: "A protein complex composed of two identical immunoglobulin heavy chains of an IgG2 isotype of the secretory isoform and two identical immunoglobulin light chains, held together by disulfide bonds and present in the extracellular space, in mucosal areas or other tissues, or circulating in the blood or lymph." [GOC:add, PMID:25368619]
synonym: "hIgG2/circulating" EXACT PRO-short-label [PRO:add]
synonym: "IgG2 antibody, human" EXACT [GOC:add]
synonym: "IgG antibody, human" BROAD [GOC:add]
is_a: PR:NewTerm2 ! IgG2 immunoglobulin complex (human)
relationship: has_component PR:NewTerm10 ! IgG2 heavy chain protein, secretory isoform (human)
relationship: has_component PR:000050183 ! immunoglobulin light chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm19
name: IgG3 immunoglobulin complex, circulating (human)
def: "A protein complex composed of two identical immunoglobulin heavy chains of an IgG3 isotype of the secretory isoform and two identical immunoglobulin light chains, held together by disulfide bonds and present in the extracellular space, in mucosal areas or other tissues, or circulating in the blood or lymph." [GOC:add, PMID:25368619]
synonym: "hIgG3/circulating" EXACT PRO-short-label [PRO:add]
synonym: "IgG3 antibody, human" EXACT [GOC:add]
synonym: "IgG antibody, human" BROAD [GOC:add]
is_a: PR:NewTerm3 ! IgG3 immunoglobulin complex (human)
relationship: has_component PR:NewTerm11 ! IgG3 heavy chain protein, secretory isoform (human)
relationship: has_component PR:000050183 ! immunoglobulin light chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm20
name: IgG4 immunoglobulin complex, circulating (human)
def: "A protein complex composed of two immunoglobulin heavy chains of an IgG4 isotype of the secretory isoform and two immunoglobulin light chains, held together by disulfide bonds and present in the extracellular space, in mucosal areas or other tissues, or circulating in the blood or lymph. Note that secreted IgG4 often undergoes half-molecule exchange (exchange of one heavy chain-light chain arm for another) to form bivalent complexes (two independent binding sites) that are functionally molevalent in most biological situations." [GOC:add, PMID:25368619]
synonym: "hIgG4/circulating" EXACT PRO-short-label [PRO:add]
synonym: "IgG4 antibody, human" EXACT [GOC:add]
synonym: "IgG antibody, human" BROAD [GOC:add]
is_a: PR:NewTerm4 ! IgG4 immunoglobulin complex (human)
relationship: has_component PR:NewTerm12 ! IgG4 heavy chain protein, secretory isoform (human)
relationship: has_component PR:000050183 ! immunoglobulin light chain protein (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm21
name: IgG1 B cell receptor complex (human)
def: "A human IgG1 immunoglobulin complex that is present in the plasma membrane of B cells and is composed of two identical immunoglobulin heavy chains of the membrane-bound isoform of the IgG1 isotype, two identical immunoglobulin light chains (kappa or lambda), and a signaling subunit, a heterodimer of the Ig-alpha and Ig-beta proteins." [GOC:add, ISBN:0781765196, PMID:17496345]
synonym: "hIgG1/B-cell-receptor" EXACT PRO-short-label [PRO:add]
synonym: "membrane-bound IgG1, human" EXACT [GOC:add]
synonym: "membrane-bound IgG, human" BROAD [GOC:add]
synonym: "surface IgG1, human" EXACT [GOC:add]
synonym: "surface IgG, human" BROAD [GOC:add]
is_a: PR:NewTerm1 ! IgG1 immunoglobulin complex (human)
relationship: part_of GO:0005886 ! plasma membrane
relationship: part_of CL:0000236 ! B cell
relationship: has_component PR:NewTerm13 {cardinality="2"} ! IgG1 heavy chain protein, membrane-bound isoform (human)
relationship: has_component PR:000050183 {cardinality="2"} ! immunoglobulin light chain protein (human)
relationship: has_component PR:P11912 {cardinality="1"} ! B-cell antigen receptor complex-associated protein alpha chain (human)
relationship: has_component PR:P40259 {cardinality="1"} ! B-cell antigen receptor complex-associated protein beta chain (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm22
name: IgG2 B cell receptor complex (human)
def: "A human IgG2 immunoglobulin complex that is present in the plasma membrane of B cells and is composed of two identical immunoglobulin heavy chains of the membrane-bound isoform of the IgG2 isotype, two identical immunoglobulin light chains (kappa or lambda), and a signaling subunit, a heterodimer of the Ig-alpha and Ig-beta proteins." [GOC:add, ISBN:0781765196, PMID:17496345]
synonym: "hIgG2/B-cell-receptor" EXACT PRO-short-label [PRO:add]
synonym: "membrane-bound IgG2, human" EXACT [GOC:add]
synonym: "membrane-bound IgG, human" BROAD [GOC:add]
synonym: "surface IgG2, human" EXACT [GOC:add]
synonym: "surface IgG, human" BROAD [GOC:add]
is_a: PR:NewTerm2 ! IgG2 immunoglobulin complex (human)
relationship: part_of GO:0005886 ! plasma membrane
relationship: part_of CL:0000236 ! B cell
relationship: has_component PR:NewTerm14 {cardinality="2"} ! IgG2 heavy chain protein, membrane-bound isoform (human)
relationship: has_component PR:000050183 {cardinality="2"} ! immunoglobulin light chain protein (human)
relationship: has_component PR:P11912 {cardinality="1"} ! B-cell antigen receptor complex-associated protein alpha chain (human)
relationship: has_component PR:P40259 {cardinality="1"} ! B-cell antigen receptor complex-associated protein beta chain (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm23
name: IgG3 B cell receptor complex (human)
def: "A human IgG3 immunoglobulin complex that is present in the plasma membrane of B cells and is composed of two identical immunoglobulin heavy chains of the membrane-bound isoform of the IgG3 isotype, two identical immunoglobulin light chains (kappa or lambda), and a signaling subunit, a heterodimer of the Ig-alpha and Ig-beta proteins." [GOC:add, ISBN:0781765196, PMID:17496345]
synonym: "hIgG3/B-cell-receptor" EXACT PRO-short-label [PRO:add]
synonym: "membrane-bound IgG3, human" EXACT [GOC:add]
synonym: "membrane-bound IgG, human" BROAD [GOC:add]
synonym: "surface IgG3, human" EXACT [GOC:add]
synonym: "surface IgG, human" BROAD [GOC:add]
is_a: PR:NewTerm3 ! IgG3 immunoglobulin complex (human)
relationship: part_of GO:0005886 ! plasma membrane
relationship: part_of CL:0000236 ! B cell
relationship: has_component PR:NewTerm15 {cardinality="2"} ! IgG3 heavy chain protein, membrane-bound isoform (human)
relationship: has_component PR:000050183 {cardinality="2"} ! immunoglobulin light chain protein (human)
relationship: has_component PR:P11912 {cardinality="1"} ! B-cell antigen receptor complex-associated protein alpha chain (human)
relationship: has_component PR:P40259 {cardinality="1"} ! B-cell antigen receptor complex-associated protein beta chain (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: PR:NewTerm24
name: IgG4 B cell receptor complex (human)
def: "A human IgG4 immunoglobulin complex that is present in the plasma membrane of B cells and is composed of two identical immunoglobulin heavy chains of the membrane-bound isoform of the IgG4 isotype, two identical immunoglobulin light chains (kappa or lambda), and a signaling subunit, a heterodimer of the Ig-alpha and Ig-beta proteins." [GOC:add, ISBN:0781765196, PMID:17496345]
synonym: "hIgG4/B-cell-receptor" EXACT PRO-short-label [PRO:add]
synonym: "membrane-bound IgG4, human" EXACT [GOC:add]
synonym: "membrane-bound IgG, human" BROAD [GOC:add]
synonym: "surface IgG4, human" EXACT [GOC:add]
synonym: "surface IgG, human" BROAD [GOC:add]
is_a: PR:NewTerm4 ! IgG4 immunoglobulin complex (human)
relationship: part_of GO:0005886 ! plasma membrane
relationship: part_of CL:0000236 ! B cell
relationship: has_component PR:NewTerm16 {cardinality="2"} ! IgG4 heavy chain protein, membrane-bound isoform (human)
relationship: has_component PR:000050183 {cardinality="2"} ! immunoglobulin light chain protein (human)
relationship: has_component PR:P11912 {cardinality="1"} ! B-cell antigen receptor complex-associated protein alpha chain (human)
relationship: has_component PR:P40259 {cardinality="1"} ! B-cell antigen receptor complex-associated protein beta chain (human)
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens

**Comment by nataled** [comment]
This unfortunately came in as we were in the end stages of a new PRO release, so these won't make it in this time around. Just FYI.

Regarding your options, with 2A favored, can you confirm that pursuing that option involves no changes to these new terms or existing PRO terms?

**Comment by addiehl** [comment]
Option 2A involves requesting a change to the definition of GO:0071735, immunoglobulin complex, to change it from

"A protein complex composed of two identical immunoglobulin heavy chains of an IgG isotype and two identical immunoglobulin light chains, held together by disulfide bonds."
to
"A protein complex composed of two immunoglobulin heavy chains of an IgG isotype and two immunoglobulin light chains, held together by disulfide bonds."

The second definition is less restrictive than the first and thus should present no issues with the more restrictive definitions for IgG1, IgG2, and IgG3 complexes.

I believe it is also semantically compatible with the definition of its parent, GO:0019814 immunoglobulin complex, which reads

"A protein complex that in its canonical form is composed of two identical immunoglobulin heavy chains and two identical immunoglobulin light chains, held together by disulfide bonds and sometimes complexed with additional proteins."

The use of the phrase "in its canonical form" suggests variant forms do exist, such as circulating IgG4.

If you would prefer I take this issue up with GO first before proceeding with this request, I can do so.

**Comment by nataled** [comment]
No, I can do this while the GO issue is addressed.

**Comment by nataled** [comment]
Question: Are those secretory and membrane-bound isoforms found in other organisms? I'm thinking it might be worthwhile making the species non-specific versions.

**Comment by addiehl** [comment]
Yes, in most vertebrates from fish on up (apart from the Agnathan fish:  lamprey and hagfish) there are membrane and secreted forms.

However, in fish, amphibians, reptiles, and even birds, not all isotopes have the same names.  Fish have IgM, IgD, IgT, and IgW (depending on the taxa), amphibians have IgM, IgD, IgX, and IgY, reptiles IgM, IgY, and IgA, Birds IgM, IgY, and IgA, and mammals IgM, IgG, IgA, IgD, and IgE (PMID:22394174).

**Comment by nataled** [comment]
If each of these are orthologs (for example IgT heavy chains = IgA heavy chains), then it is okay.

**Comment by addiehl** [comment]
I don't know how well the orthology holds, although the shared nomenclature such as IgM and IgD suggests general orthologies over large phylogenetic distances. I would probably need to do some deeper reading myself to know better. These are of course genes of the immune system, which tend to have greater variation and selective pressures than many other gene families.

**Comment by nataled** [comment]
For the specific IgG subtypes (IgG1, IgG2, etc), and for the specific subtypes thereof (secretory, membrane), which is the more important parent-child relationship? For example:

(a) IgG1 secretory isoform is_a IgG1
  or
(b) IgG1 secretory isoform is_a secretory isoform

Obviously we'd like to say both, but at the moment this isn't possible. So, is it more important that all IgG subtypes stay with others from that same subtype, or that all secretory isoforms stay with other secretory isoforms?

**Comment by addiehl** [comment]
I think IgG1 secretory isoform is_a IgG1 is the relationship to highlight.

**Comment by nataled** [comment]
Another question, this time about the complexes. Previous Ig complexes allowed for monomeric and multimeric forms. I checked the literature and found such can also be true for IgG complexes, though it seems these might be experimental/clinical artifacts. Is it necessary to allow for such things? For example, if allowed, we'll want to describe the components of the IgG complexes in terms of 'in the monomeric form' as we did before.

**Comment by addiehl** [comment]
I don't recall seeing this finding for the IgGs.  Can you point me to a paper or two?

**Comment by nataled** [comment]
Here's one: https://www.ncbi.nlm.nih.gov/pubmed/21338382

I just searched Google with 'IgG dimer' to see if there were any examples.

**Comment by addiehl** [comment]
Per the paper you cite, the authors suggest these are idiotype‐antiidiotype Ab pairs.  An antiidiotype is an antibody that binds another antibody, typically at the second antibody's binding site, which can antigenic, being a novel sequence.  The formation of idiotype‐antiidiotype Ab pairs is considered to be a form of immune regulation of antibody responses by forming counter antibody responses.  While these pairs appear as dimers, they are not really a proper protein complex per se, since the antibodies involved may be of different isotopes.

Based on this paper and others I have looked at, I think we can ignore multimeric forms of IgGs for the moment.  Other isotopes like IgA and IgM have bone fide multimeric forms, of course.

**Comment by nataled** [comment]
Finished! Below is the mapping from your temporary identifiers to the permanent ones. The stanzas themselves are in the attached document. Please let me know if there are any issues.

PR:NewTerm5	= PR:000050291
PR:NewTerm6	= PR:000050292
PR:NewTerm7	= PR:000050293
PR:NewTerm8	= PR:000050294
PR:NewTerm9	= PR:000050297
PR:NewTerm10	= PR:000050298
PR:NewTerm11	= PR:000050299
PR:NewTerm12	= PR:000050300
PR:NewTerm13	= PR:000050301
PR:NewTerm14	= PR:000050302
PR:NewTerm15	= PR:000050303
PR:NewTerm16	= PR:000050304
PR:NewTerm1	= PR:000050305
PR:NewTerm2	= PR:000050306
PR:NewTerm3	= PR:000050307
PR:NewTerm4	= PR:000050308
PR:NewTerm17	= PR:000050309
PR:NewTerm18	= PR:000050310
PR:NewTerm19	= PR:000050311
PR:NewTerm20	= PR:000050312
PR:NewTerm21	= PR:000050313
PR:NewTerm22	= PR:000050314
PR:NewTerm23	= PR:000050315
PR:NewTerm24	= PR:000050316
[IgG.obo.txt](https://github.com/PROconsortium/PRoteinOntology/files/4645298/IgG.obo.txt)
