### ISSUE TITLE
List of PRO terms representing all taxon-specific proteins

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#192]
We need to have a list of PRO terms that represent "all proteins in this organism". Such a list actually already exists and is provided with each release, but at the moment is incomplete. I will work on creating the list at release time (will be easy to do), but I wanted to find out what format to use. The existing file (taxbased_protein.dat) is just a single-column list of PRO terms, like:
<pre>PR:000000001
PR:000018263
PR:000029053
PR:000029031
PR:000029043
PR:000029065
PR:000029060
PR:000036194
</pre>

A few questions:
1) @jz26 I recall this file was needed by you, or maybe it was @hongzhanhuang, for web site purposes. I'm not sure if that's still the case. Do you recall? Well, more to the point, is it still needed?

2) @chumingc I didn't quite catch what you said regarding what information you needed. Was it a mapping between the taxon ID and the PRO ID for such terms? And I think the name of...? Would this work:

NCBITaxon:9606<tab>PR:000029067<tab>WHICHEVER NAME YOU NEEDED

3) On the chance that taxbased_protein.dat is still needed, would it be best to modify that file according to the needs above, or to create a new file?

**Comment by chumingc** [comment]
I think this will work. We show people "Homo sapiens [9606]” and do the mapping behind the scene.

Homo sapiens [9606]	PR:000029067

**Comment by jz26** [comment]
On Fri, Jul 17, 2020 at 3:29 PM Darren A. Natale <notifications@github.com>
wrote:

> We need to have a list of PRO terms that represent "all proteins in this
> organism". Such a list actually already exists and is provided with each
> release, but at the moment is incomplete. I will work on creating the list
> at release time (will be easy to do), but I wanted to find out what format
> to use. The existing file (taxbased_protein.dat) is just a single-column
> list of PRO terms, like:
>
> PR:000000001
> PR:000018263
> PR:000029053
> PR:000029031
> PR:000029043
> PR:000029065
> PR:000029060
> PR:000036194
>
> A few questions:
>
>    1.
>
>    @jz26 <https://github.com/jz26> I recall this file was needed by you,
>    or maybe it was @hongzhanhuang <https://github.com/hongzhanhuang>, for
>    web site purposes. I'm not sure if that's still the case. Do you recall?
>    Well, more to the point, is it still needed?
>
>


*I don't recall. Do you have more clues?*

**Comment by nataled** [comment]
@jz26 I believe it might have been used to suppress showing a giant list of children for the listed PRO terms.

**Comment by nataled** [comment]
Based on offline conversations, it has been confirmed that the existing file listing the terms of interest can be adapted to another use. I will let you know when it is ready.

**Comment by nataled** [comment]
@chumingc the format you suggested will not be easily parseable in all cases, as some taxon names have square brackets within. Instead, I'll produce the following:

taxon_name<tab>taxon_number<tab>PRO_identifier

You can find an example file at /home/dnatale/data/ontologies/for_release/taxbased_protein.dat on Hershey. Let me know if that's suitable. I can easily revise.

In the future, the file will be found at /data/pir/projects/pro/releaseNUM where NUM is the release number (next one being 61).
