### ISSUE TITLE
Duplicate labels?

### ISSUE THREAD

**Issue by callahantiff** [PROconsortium/PRoteinOntology#194]
I noticed that **[`PR:000044428`](https://proconsortium.org/app/entry/PR%3A000044428/)** and **[`PR:000007812`](https://proconsortium.org/app/entry/PR%3A000007812/)** have the same labels. Given that `PR:000007812` is the translation product of the human gene GALE, should this class have a label that includes human? I also noticed that there is a human version of this protein too (`PR_Q14376`). Please advise. 

Thank you so much for your help!

**Comment by nataled** [comment]
Thank you for catching this! The label for PR:000044428 has been changed to "UDP-glucose 4-epimerase galE1" while the label for PR:000007812 will remain the same. The change will take effect with the next release, coming next week.

One clarification: PR:000007812 is the translation product of the human GALE *or a 1:1 ortholog thereof* and thus is a taxon-neutral term, while the human version is as you noted.

Please let me know if you need further assistance.

Best regards,
Darren Natale

**Comment by callahantiff** [comment]
> Thank you for catching this! The label for PR:000044428 has been changed to "UDP-glucose 4-epimerase galE1" while the label for PR:000007812 will remain the same. The change will take effect with the next release, coming next week.
> 
> One clarification: PR:000007812 is the translation product of the human GALE _or a 1:1 ortholog thereof_ and thus is a taxon-neutral term, while the human version is as you noted.
> 
> Please let me know if you need further assistance.
> 
> Best regards,
> Darren Natale

Hi Darren-

Thanks so much for the update and for clarifying this for me, the taxon-neutral point makes perfect sense. 

Thanks to you and the rest of the PRO Consortium for creating and maintaining this resource. I really appreciate all of the hard work; I'm a HUGE fan! 😄 

-Tiffany

**Comment by nataled** [comment]
Glad to hear it! Out of curiosity, for which project do you use PRO? It's always good to know the users, in hopes of finding better ways of meeting their needs :)

**Comment by callahantiff** [comment]
Absolutely, thanks for asking! PRO is a central component of two of my projects:
- **[`PheKnowLator`](https://github.com/callahantiff/PheKnowLator)**:  A Python framework for building large-scale heterogeneous biomedical knowledge graphs. For this project, we also release a knowledge graph modeling human disease mechanisms for which PRO is a staple in our base representation.
- **[`OMOP2OBO`](https://github.com/callahantiff/OMOP2OBO)**: A hospital-scale mapping between diagnosis, medication, and laboratory test concepts in the [OMOP Common Data Model](https://www.ohdsi.org/data-standardization/the-common-data-model/) to several OBO ontologies. For this project, with respect to PRO, I create and maintain mappings between specific medications and laboratory test terms.

**Comment by nataled** [comment]
Wonderful! Thanks! Don't be shy about requesting any terms you need. We're especially interested in making sure we have terms representing biomarkers.

**Comment by callahantiff** [comment]
Thanks so much, I will definitely follow-up once we have a first release.
