### ISSUE TITLE
Term issue: New term for cut12 phosphoforms

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#197]
Hi @nataled, please coul I gegt Phospho forms of cut12 (SPB signalling adaptor)

PMID:23333317
O59755

1. Unphosphorylated form ( T75,T78) I don't know about the P-status of any other residues
2. T75 phosphorylated
3. T78 phosphorylated
3. T75,T78 phosphorylated

**Comment by nataled** [comment]
Hi Val! Your terms are ready. I added one for the parent as well:
  PR:000050397  parent
  PR:000050398  Unphosphorylated form ( T75,T78)
  PR:000050400  T75 phosphorylated
  PR:000050401  T78 phosphorylated
  PR:000050399  T75,T78 phosphorylated

[Term]
id: PR:000050397
name: spindle pole body-associated protein cut12 (Schizosaccharomyces pombe)
def: "A protein that is a translation product of the cut12 gene in Schizosaccharomyces pombe." [PRO:DAN]
comment: Category=organism-gene. Requested by=PomBase.
synonym: "Spom-cut12" EXACT PRO-short-label [PRO:DAN]
synonym: "cell untimely torn protein 12 (Schizosaccharomyces pombe)" EXACT [UniProtKB:O59755]
synonym: "cut12" RELATED Gene-based [UniProtKB:O59755]
synonym: "SPBC649.05" RELATED Gene-based [UniProtKB:O59755]
synonym: "stf1" RELATED Gene-based [UniProtKB:O59755]
intersection_of: PR:000000001 ! protein
intersection_of: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
intersection_of: has_gene_template PomBase:SPBC649.05 ! cut12 (Schizosaccharomyces pombe)

[Term]
id: PR:000050398
name: spindle pole body-associated protein cut12 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A spindle pole body-associated protein cut12 (Schizosaccharomyces pombe) that has not been phosphorylated at positions equivalent to Thr-75 and Thr-78 of the amino acid sequence represented by UniProtKB:O59755. Example: UniProtKB:O59755, Thr-75/Thr-78, PR:000026291." [PRO:DAN, PomBase:VW, PMID:23333317]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-cut12/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O59755, Thr-75/Thr-78, PR:000026291" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050397 ! spindle pole body-associated protein cut12 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050399
name: spindle pole body-associated protein cut12 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A spindle pole body-associated protein cut12 (Schizosaccharomyces pombe) that has been phosphorylated at positions equivalent to Thr-75 and Thr-78 of the amino acid sequence represented by UniProtKB:O59755. Example: UniProtKB:O59755, Thr-75/Thr-78, MOD:00047." [PRO:DAN, PomBase:VW, PMID:23333317]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-cut12/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O59755, Thr-75/Thr-78, MOD:00047" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050397 ! spindle pole body-associated protein cut12 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050400
name: spindle pole body-associated protein cut12 phosphorylated 2 (Schizosaccharomyces pombe)
def: "A spindle pole body-associated protein cut12 (Schizosaccharomyces pombe) that has been phosphorylated at positions equivalent to Thr-75 of the amino acid sequence represented by UniProtKB:O59755. Example: UniProtKB:O59755, Thr-75, MOD:00047." [PRO:DAN, PomBase:VW, PMID:23333317]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-cut12/Phos:2" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O59755, Thr-75, MOD:00047" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050397 ! spindle pole body-associated protein cut12 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050401
name: spindle pole body-associated protein cut12 phosphorylated 3 (Schizosaccharomyces pombe)
def: "A spindle pole body-associated protein cut12 (Schizosaccharomyces pombe) that has been phosphorylated at positions equivalent to Thr-78 of the amino acid sequence represented by UniProtKB:O59755. Example: UniProtKB:O59755, Thr-78, MOD:00047." [PRO:DAN, PomBase:VW, PMID:23333317]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-cut12/Phos:3" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O59755, Thr-78, MOD:00047" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050397 ! spindle pole body-associated protein cut12 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

Best regards,
Darren

**Comment by ValWood** [comment]
Amazing! thanks!

**Comment by ValWood** [comment]
Hi @nataled. this might seem like a daft  question, and I may have asked before and forgotten, but it would be nice if, for display purposes we could just extract the actual residues from the entry. These seem a little bit buried in the synonym. 
It would be really nice if these was a "residues" field and a "modification" field.

**Comment by nataled** [comment]
Hi Val, I'm afraid I don't quite understand what you mean by 'extract the actual residues from the entry'. Can you explain?

**Comment by ValWood** [comment]
So we need a computational way, based on the ID to extract the residues and the modification out of the entry.

Thr-78 (phosphorylated)

I guess it is possible to do this, but it is a bit buried. 
We could use
synonym: "UniProtKB:O59755, Thr-78, MOD:00047"
but our parser will need to figure out which synonym has the relevant information, and it relies on the information *always* bing in the same order, and comma separated.

**Comment by nataled** [comment]
You're in luck, because the synonym with the information you need is always labeled "PRO-proteoform-std" and, as the name of the synonym type indicates, it is a standardized representation of modifications. Some updates are in the works--mostly to handle glycans--but the basic description is given in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5210558/ (figure 1).

**Comment by ValWood** [comment]
excellent! thanks!

**Comment by nataled** [comment]
I don't think there are any edge cases for S. pombe, but just let me know if you come across an example that is confusing to you.
