### ISSUE TITLE
Provide more information for obsolete terms

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#200]
Obsolete terms often have a 'replaced_by' or 'consider' tag. In either case, we should probably provide that information, along with a link to the alternative term. For replacements, we might consider automatically forwarding (though that might be confusing to users).

**Comment by Julie-Cowart** [comment]
I will add a notification at top if is_obsolete: true is in the obo and provide a link to the new term if replaced_by or consider exist

**Comment by Julie-Cowart** [comment]
Live on test site. I used the same font and position as the warning notice if someone uses an alt_id. 

with replace by https://proconsortium.org/app_test/entry/PR%3AP31154/
with consider https://proconsortium.org/app_test/entry/PR%3AQ30KQ2/
without neither https://proconsortium.org/app_test/entry/PR%3AQ494X1/

**Comment by nataled** [comment]
These look good. I'm wondering if we can provide more info on the 'consider' set. Unlike 'replaced by', consider means the alternative is inexact (the example you provided is one that would need two different terms to equal the single obsolete term). I'd say go live with it for now. I want to look into the possibility of listing all the 'considers' that would be needed.

**Comment by nataled** [comment]
Multiple 'consider' lines are allowed, and I've updated the _wv with any additional lines needed (there are only a few). Likely it'll be necessary for the upcoming PRO update to be in place on the test site before testing can be done.

**Comment by nataled** [comment]
All looks well. Closing this issue.

**Comment by Julie-Cowart** [comment]
please don't close the issue until its in production. Otherwise it may never end up there.

**Comment by nataled** [comment]
Sorry! I was following this: "Once 62 is on the test site, the issues need to be rechecked and pushed to production when PRO version 62 is released and issues marked as closed" which I took to mean that the issue needed to be closed if all is well on the test site after rechecking, and that only those that were closed would be pushed.

**Comment by Julie-Cowart** [comment]
I meant they get closed when they get pushed to production since that is
usually when we close issues but in this case we can use it to mark as
tested and ready for production.
