### ISSUE TITLE
Term issue: Phospho forms of KH domain RNA-binding protein Rnc1

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#201]
Hi @nataled, please could I get Phospho forms of KH domain RNA-binding protein Rnc1 (T50)

O74919

PMID:12931193
5. Sugiura R, Kita A, Shimizu Y, Shuntoh H, Sio SO, Kuno T. 2003. Feedback regulation of MAPK signalling by an RNA-binding protein. Nature 424: 961–996. https://doi.org/10.1038/nature01907.

**Comment by nataled** [comment]
Hi Val, your term is ready! I'm presuming here that you don't need the unphosphorylated form, correct? Though your use of plural ('forms') has me wondering if I missed something...

[Term]
id: PR:000050453
name: RNA-binding protein rnc1 phosphorylated 1 (Schizosaccharomyces pombe)
def: "An RNA-binding protein rnc1 (Schizosaccharomyces pombe) that has been phosphorylated at the position equivalent to Thr-50 of the amino acid sequence represented by UniProtKB:O74919. Example: UniProtKB:O74919, Thr-50, MOD:00047." [PRO:DAN, PomBase:VW, PMID:12931193]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-rnc1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O74919, Thr-50, MOD:00047" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050452 ! RNA-binding protein rnc1 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
Thanks, very fast as usual.
I do now in fact need the unphosphorylated form for a different publication:
PMID:31911490

and a fully phosphorylated form
T45, T50, T171, T177, S278, S286

Thanks again,

Val

**Comment by nataled** [comment]
New terms below. I assumed that you needed two unphosphorylated terms, one for the T50 case and one for the multiT/multiS case. If this is incorrect, please let me know.

Summary:
phos T50 = PR:000050453
unphos T50 = PR:000050454
phos T45, T50, T171, T177, S278, S286 = PR:000050455
unphos T45, T50, T171, T177, S278, S286 = PR:000050456

[Term]
id: PR:000050454
name: RNA-binding protein rnc1 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "An RNA-binding protein rnc1 (Schizosaccharomyces pombe) that has not been phosphorylated at the position equivalent to Thr-50 of the amino acid sequence represented by UniProtKB:O74919. Example: UniProtKB:O74919, Thr-50, PR:000026291." [PRO:DAN, PomBase:VW, PMID:31911490]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-rnc1/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O74919, Thr-50, PR:000026291" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050452 ! RNA-binding protein rnc1 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050455
name: RNA-binding protein rnc1 phosphorylated 2 (Schizosaccharomyces pombe)
def: "An RNA-binding protein rnc1 (Schizosaccharomyces pombe) that has been phosphorylated at positions equivalent to Thr-45, Thr-50, Thr-171, Thr-177, Ser-278, and Ser-286 of the amino acid sequence represented by UniProtKB:O74919. Example: UniProtKB:O74919, Thr-45/Thr-50/Thr-171/Thr-177, MOD:00047|Ser-278/Ser-286, MOD:00046." [PRO:DAN, PomBase:VW, PMID:31911490]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-rnc1/Phos:2" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O74919, Thr-45/Thr-50/Thr-171/Thr-177, MOD:00047|Ser-278/Ser-286, MOD:00046" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050452 ! RNA-binding protein rnc1 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050456
name: RNA-binding protein rnc1 unphosphorylated 2 (Schizosaccharomyces pombe)
def: "An RNA-binding protein rnc1 (Schizosaccharomyces pombe) that has not been phosphorylated at positions equivalent to Thr-45, Thr-50, Thr-171, Thr-177, Ser-278, and Ser-286 of the amino acid sequence represented by UniProtKB:O74919. Example: UniProtKB:O74919, Thr-45/Thr-50/Thr-171/Thr-177/Ser-278/Ser-286, PR:000026291." [PRO:DAN, PomBase:VW, PMID:31911490]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-rnc1/UnPhos:2" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O74919, Thr-45/Thr-50/Thr-171/Thr-177/Ser-278/Ser-286, PR:000026291" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050452 ! RNA-binding protein rnc1 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
Thanks!
