### ISSUE TITLE
Term issue: cdc12 phospho forms

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#205]
PMID:29343550

P18296
 unphopshorylated on T20, T22, S64, T95, T151, S463
and
cdc12 phopshorylated on T20, T22, S64, T95, T151, S463

**Comment by nataled** [comment]
Hi Val,
Can you clarify which protein(s) this request is for? The PMID is about cdc12, the UniProtKB is cut1, and the gene given is cut12. Are you asking for unphosphorylated cut1 and phosphorylated cut12? The paper mentions neither...

**Comment by nataled** [comment]
Checking the mentioned positions, it seems to be cdc12. Q10059. Is that correct?

**Comment by ValWood** [comment]
yes sorry cdc12!

**Comment by nataled** [comment]
Looks like the phosphorylated form was requested some time ago. I reproduce that information here for convenience, along with the new unphosphorylated form:

Phos:   PR:000044735   cdc12/Phos:(T20,T22,S64,T95,T151,S463)

UnPhos:    PR:000050464   cdc12/UnPhos:(T20,T22,S64,T95,T151,S463)

[Term]
id: PR:000044735
name: cell division control protein 12 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A cell division control protein 12 (Schizosaccharomyces pombe) that has been phosphorylated on residues equivalent to Thr-20, Thr-22, Ser-64, Thr-95, Thr-151 and Ser-463 of the amino acid sequence represented by UniProtKB:Q10059. Example: UniProtKB:Q10059, Thr-20/Thr-22/Thr-95/Thr-151, MOD:00047|Ser-64/Ser-463, MOD:00046." [PRO:DAN, PomBase:VW, PMID:29343550]
comment: Category=organism-modification. Kinase=("cdc2"; PR:000036301; Thr-20/Thr-22/Ser-64/Thr-95/Thr-151/Ser-463). Requested by=PomBase.
synonym: "Spom-cdc12/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q10059, Thr-20/Thr-22/Thr-95/Thr-151, MOD:00047|Ser-64/Ser-463, MOD:00046" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000044734 ! cell division control protein 12 (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: has_part MOD:00047 ! O-phospho-L-threonine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050464
name: cell division control protein 12 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A cell division control protein 12 (Schizosaccharomyces pombe) that has not been phosphorylated on residues equivalent to Thr-20, Thr-22, Ser-64, Thr-95, Thr-151 and Ser-463 of the amino acid sequence represented by UniProtKB:Q10059. Example: UniProtKB:Q10059, Thr-20/Thr-22/Ser-64/Thr-95/Thr-151/Ser-463, PR:000026291." [PRO:DAN, PomBase:VW, PMID:29343550]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-cdc12/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q10059, Thr-20/Thr-22/Ser-64/Thr-95/Thr-151/Ser-463, PR:000026291" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000044734 ! cell division control protein 12 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
