### ISSUE TITLE
Term issue: IgY heavy chain protein

### ISSUE THREAD

**Issue by rvita** [PROconsortium/PRoteinOntology#206]
We'd like to request the IgY heavy chain protein as a new term
https://en.wikipedia.org/wiki/Immunoglobulin_Y
similar to our past immunoglobulin term requests (like IgE heavy chain protein PR:000050258).
Thanks

**Comment by nataled** [comment]
Here is the new term:

[Term]
id: PR:000050465
name: IgY heavy chain protein
def: "An immunoglobulin heavy chain protein in which the constant region is encoded by the IgY gene segment." [PRO:DAN]
comment: Category=seqgroup. Requested by=IEDB. Note: IgY heavy chain is functionally equivalent to mammalian IgG heavy chain, but differs structurally.
synonym: "IgHY" EXACT PRO-short-label [PRO:DAN]
synonym: "immunoglobulin Y heavy chain" EXACT [PRO:DAN]
synonym: "egg yolk IgG" RELATED [PRO:DAN]
synonym: "7S-IgG" RELATED [PRO:DAN]
is_a: PR:000050174 ! immunoglobulin heavy chain protein
