### ISSUE TITLE
Term issue: glycated hemoglobin

### ISSUE THREAD

**Issue by cstoeckert** [PROconsortium/PRoteinOntology#208]
For PennTURBO and OBI, we'd like a term for human 'glycated hemoglobin' as the analyte measured in Hemoglobin A1c tests for blood sugar levels. 
It could be defined as: 'a form of hemoglobin (Hb) that is chemically linked to a sugar.'
Definition source: https://en.wikipedia.org/wiki/Glycated_hemoglobin

**Comment by nataled** [comment]
Hi Chris,

Is it desired that the term be scoped to humans only, or is a broad taxonomic scope desired? We can accommodate either.

**Comment by cstoeckert** [comment]
Our primary interest is humans but it appears that the test is also available for dogs and cats (https://www.vmdtoday.com/news/a1c-test-now-available-for-cats-and-dogs) so broader would be good.  
My interpretation like yours is that A1c is for HbA not HbF or HbA2.

**Comment by nataled** [comment]
Hi Chris,

Well, this was more involved than I expected! It seems that the definition of HbA1c has changed over the years. I'm not fully sure it has been fully standardized yet. Nonetheless, I defined it using what I believe is the latest standard, which involves a very specific amino acid modification to one of the subunits (see first term below). The second term is the requested term. Please verify that this is what you want.

[Term]
id: PR:000050468
name: hemoglobin subunit beta N-1-deoxyfructosylated 1
def: "A hemoglobin subunit beta, initiator methionine removed form that has been N-1-deoxyfructosylated at the position equivalent to Val-2 of the sequence represented by UniProtKB:P68871-1 or a 1:1 ortholog thereof. [PRO:DAN]
comment: Category=modification.
synonym: "HBB/InitMet-/dFruc:1" EXACT PRO-short-label [PRO:DAN]
synonym: "beta-N-1-deoxy fructosyl hemoglobin subunit" BROAD [PRO:DAN]
is_a: PR:000020114 ! hemoglobin subunit beta, initiator methionine removed form

[Term]
id: PR:000050469
name: hemoglobin A1c
def: "A hemoglobin complex that is composed of at least one beta-N-1-deoxy fructosyl hemoglobin subunit, in which the glycan is attached to the N-terminal valine (after initiator methionine removal) of one or both beta subunits." [PRO:DAN, PMID:9732983, Wikipedia:Glycated_hemoglobin]
comment: Category=complex. Requested by=PennTURBO. Note: The precise definition of hemoglobin A1c has evolved over time [https://medcraveonline.com/JNMR/laboratory-diagnosis-of-hba1c-a-review.html]. This PRO term is based on the most-precise definition currently in use.
synonym: "HbA1c" EXACT PRO-short-label [PRO:DAN]
synonym: "glycohemoglobin" BROAD [PMID:9732983]
synonym: "glycated hemoglobin" BROAD [PMID:9732983]
synonym: "HgbA1c" EXACT [PMID:9732983]
is_a: GO:0005833 ! hemoglobin complex
relationship: has_component PR:000050468 {minCardinality="1"} ! hemoglobin subunit beta N-1-deoxyfructosylated 1
relationship: has_component PR:000050468 {maxCardinality="2"} ! hemoglobin subunit beta N-1-deoxyfructosylated 1
relationship: has_component PR:000050026 {maxCardinality="1"} ! hemoglobin subunit beta
relationship: has_component PR:000008456 {cardinality="2"} ! hemoglobin subunit alpha

**Comment by cstoeckert** [comment]
Hi Darren,
Yes, the second term is what we want. Thanks!
