### ISSUE TITLE
Term issue: Sty1 phosphorylated and unphosphorylated forms

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#210]
Sty1 activated from 
Y173-P
T171-P
Q09892
PMID:12181336

**Comment by nataled** [comment]
This term already exists, as does the non-activated form. I added the reference and revised the names a bit:

Phos:       PR:000027503 sty1/Phos(T171,Y173)
UnPhos:  PR:000027505 sty1/UnPhos(T171,Y173)

[Term]
id: PR:000027503
name: mitogen-activated protein kinase sty1 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A mitogen-activated protein kinase HOG1 phosphorylated 1 in Schizosaccharomyces pombe. Phosphorylated on TxY motif by MAPK kinase (Wis1). Example: UniProtKB:Q09892, Thr-171, MOD:00047|Tyr-173, MOD:00048." [PomBase:MAH, PMID:20729203, PMID:7501024, PMID:9251044, PMID:12181336]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-sty1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "active PHH1" EXACT []
synonym: "active spc1" EXACT []
synonym: "active sty1" EXACT []
synonym: "sty1 activated form" EXACT []
synonym: "UniProtKB:Q09892, Thr-171, MOD:00047|Tyr-173, MOD:00048" NARROW PRO-proteoform-std [PRO:DNx]
intersection_of: PR:000027502 ! mitogen-activated protein kinase HOG1 phosphorylated 1
intersection_of: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
relationship: has_part MOD:00047 ! O-phospho-L-threonine
relationship: has_part MOD:00048 ! O4'-phospho-L-tyrosine

[Term]
id: PR:000027505
name: mitogen-activated protein kinase sty1 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A mitogen-activated protein kinase sty1 (Schizosaccharomyces pombe) that has not been phosphorylated at the MAP kinase activation motif TxY. Example: UniProtKB:Q09892, Thr-171/Tyr-173, PR:000026291." [PRO:CNA, PRO:DAN, PMID:12181336]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-sty1/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q09892, Thr-171/Tyr-173, PR:000026291" NARROW PRO-proteoform-std [PRO:DNx]
is_a: PR:000050473 ! mitogen-activated protein kinase sty1 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by nataled** [comment]
Val said: 
Sorry. I need to check this first. I searched for Sty1 in the tracker and didn't find anything.
What is the best way to look up if modifications already exist, Sorry I think I knew this but I forgot

My response:
Alas, PRO has at least 3 different methods people use to make requests. Some come in via email, others via a custom request page, and still others use the tracker. Thus, the sty1 request likely came from one of the first two (it was from Midori, some years ago). One way to find existing terms would be to search the PRO website for the name of the protein of interest as used in PRO (which, in turn, can be found just using the gene name), then search with that name (be sure to remove the organism name given at the end).

**Comment by ValWood** [comment]
I can search on UniProt ID and find all modifications for an entry, this is perfect.

cheers,

Val

**Comment by nataled** [comment]
Yes, that will work for the vast majority of cases.
