### ISSUE TITLE
Term issue:  wis1 phosphorylated/unphosphorylated

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#211]
P33886

PMID:12181336

MAPKKK phos-phorylation sites in Wis1, Ser-469, and Thr-473

**Comment by nataled** [comment]
Hi Val,

Your term is below. Two questions: (1) Do you also wish to have the non-phosphorylated version? (2) Do you know which MAPKKK phosphorylates each residue? If so I will add that information to the term.

[Term]
id: PR:000050475
name: protein kinase wis1 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A protein kinase wis1 (Schizosaccharomyces pombe) that has been phosphorylated on residues equivalent to Ser-469 and Thr-473 of the amino acid sequence represented by UniProtKB:P33886. Example: UniProtKB:P33886, Ser-469, MOD:00046|Thr-473, MOD:00047." [PRO:DAN, PomBase:VW, PMID:12181336]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-wis1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:P33886, Ser-469, MOD:00046|Thr-473, MOD:00047" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050474 ! protein kinase wis1 (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: has_part MOD:00047 ! O-phospho-L-threonine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
Yes please for the unphoshphorylated form.

My understanding was that either win1  O74304 or wis4  O14299 can phosphorylate both residues, but I will double check this....

Wis4 can definitely add both PMID:9718372

**Comment by nataled** [comment]
Unphosphorylated form. I added the kinase info to the phosphorylated version.

[Term]
id: PR:000050476
name: protein kinase wis1 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A protein kinase wis1 (Schizosaccharomyces pombe) that has not been phosphorylated on residues equivalent to Ser-469 and Thr-473 of the amino acid sequence represented by UniProtKB:P33886. Example: UniProtKB:P33886, Ser-469/Thr-473, PR:000026291." [PRO:DAN, PomBase:VW, PMID:12181336]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-wis1/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:P33886, Ser-469/Thr-473, PR:000026291" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050474 ! protein kinase wis1 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
