### ISSUE TITLE
NTR: S. pombe Rgo1, GTP bound form

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#212]
PMID:10651902
Q09914
S. pombe Rho1, GTP bound form

(I don't know the precise binding site?)

**Comment by nataled** [comment]
Hi Val,
Here's your term!

[Term]
id: PR:000050473
name: GTP-binding protein rho1, GTP-bound form (Schizosaccharomyces pombe)
def: "A GTP-binding protein rho1 (Schizosaccharomyces pombe) that is non-covalently bound to GTP." [PRO:DAN, PomBase:VW, PMID:10651902]
comment: Category=organism-complex. Requested by=PomBase.
synonym: "Spom-rho1/GTP+" EXACT PRO-short-label [PRO:DAN]
intersection_of: PR:000050474 ! GTP-binding protein rho1 (Schizosaccharomyces pombe)
intersection_of: non-covalently_bound_to CHEBI:15996 ! GTP
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
Thanks. A bit slow though ;)

**Comment by nataled** [comment]
That's because I'm actually off work today :)

**Comment by ValWood** [comment]
That explains it!
