### ISSUE TITLE
Issues with glycans

### ISSUE THREAD

**Issue by Julie-Cowart** [PROconsortium/PRoteinOntology#216]
We have a new format for PRO-proteoform-std to show glygans (new in release 62) and I am creating this issue to track the discussions of the problems that may come up. The format is:

synonym: "UniProtKB:A1L4H1-1, Ser-1466, MOD:00002~GNO:G43417UB" NARROW PRO-proteoform-std [PRO:DNx]

This change to the format is not handled properly in the parser and so the modifications are not going to show in MSA or cytoscape. And there probably other bugs that may crop up.

Also @nataled writes:
There is one other 'change' with respect to PRO-proteoform-std lines, and that is that there can be multiple lines. I had been using those as a way to detect already-existing terms, but it failed because, for example, I'd have the proteoform in PRO defined with respect to some isoform but search with the canonical. To resolve that issue, I sometimes added both types of lines (one referencing the main identifier and and one referencing the canonical isoform):
synonym: "UniProtKB:P07492, 24-148" EXACT PRO-proteoform-std [PRO:DAN]
synonym: "UniProtKB:P07492-1, 24-148" NARROW PRO-proteoform-std [PRO:DAN]

**Comment by Julie-Cowart** [comment]
Checked on test site and had to do a small patch to make the links work properly (so that MOD: and GNO: are detected as two ids separated by a ~ and not one with a wierd id). Fixed now and it looks like all else is ok (see https://proconsortium.org/app_test/entry/PR%3A000050601/) minus the lack of a MSA view which has to be fixed in the parser so will have to wait until next release.

**Comment by nataled** [comment]
Nice work on that. I'm not sure when this might happen, but I'm pretty sure that some future Reactome-based entries will have this type of syntax, though not necessarily using GNO (they sometimes use CHEBI in the same way this is being used; that is, as a specific linkage to some more general indication of modification). The solution will thus need to be generalized in some way (perhaps by using a regex that checks against 'full word' prefixes; that is, bounded by non-alphanumeric characters).

**Comment by Julie-Cowart** [comment]
Oh it is generalized. I actually just added ~ as a word separator so it will work with any prefix.

**Comment by Julie-Cowart** [comment]
Also the term referenced above with 2 PRO-proteoform-std synonyms does show both synonyms. https://proconsortium.org/app_test/entry/PR%3A000050383/ so the only issue is the MSA view. Though I realize now that isn't just for glygans.

**Comment by Julie-Cowart** [comment]
The links for glycans are fixed and in production. They could be handled better on the backend if we ever want to be able to do more with it but for now I'm closing this issue (and forking the multiple PRO-proteoform-std issue into #247).
