### ISSUE TITLE
DAG view links

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#219]
To reproduce, go to https://proconsortium.org/app/entry/PR:000025934/ (our sample entry), click to see the DAG view, and add the following columns to the view:

Reactome - each part of the identifier (between the dashes) is being linked separately instead of as a unit (R-HSA-177099). There is also one that shows up in the column for the parent term, PR:000000650. There is no Reactome xref or even evidence for this entry.

UniProtKB - sometimes there is an extra semi-colon.

HGNC -the links are incorrect, going to
   http://www.genenames.org/data/hgnc_data.php?hgnc_id=HGNC:6768
 instead of the correct link, 
   http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=6768.

PIRSF - the links are going to 'proconsortium.org' instead of 'proteininformationresource.org' (all else is fine).

**Comment by Julie-Cowart** [comment]
I'm not sure who is in charge of the DAG view but it isn't me. It is done in perl outside of django. Jian perhaps?

**Comment by nataled** [comment]
Oops, sorry. I'll reassign.

**Comment by jz26** [comment]
The issues are all addressed.

**Comment by nataled** [comment]
Confirmed, thanks!
