### ISSUE TITLE
PRO web usage statistics

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#221]
We need to implement some tracking mechanism. Google analytics will need to be installed into the banners or footer:
Chuming - LOD pages
Jian - general pages
Julie - entry pages

Hongzhan has the necessary code.

**Comment by chumingc** [comment]
Done for https://lod.proconsortium.org/index.html

Chuming

**Comment by nataled** [comment]
From @jz26 

the google analytic code for the PRO web pages (between two dash  lines):

-----------------------------------------------
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-4232355-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
------------------------------------------------

An example from the PIR website home page (@ the bottom):

view-source:https://proteininformationresource.org/pirwww/index.shtml

(copy the entire line into you web address bar)

**Comment by jz26** [comment]
done.
-jz

**Comment by Julie-Cowart** [comment]
Done for the Entry pages as well as the cytoscape and msa pages.
