### ISSUE TITLE
Term issue: fin1 phosphorylated

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#222]
O13839
fin1 - phsphorylated on S377,S698,S526 
(by sid2)
PMID:22684255

**Comment by nataled** [comment]
Hi Val, Hope you're enjoying your holidays! Your term is below:

PR:000050481 fin1/Phos(S377/S526/S698)

[Term]
id: PR:000050481
name: G2-specific protein kinase fin1 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A G2-specific protein kinase fin1 (Schizosaccharomyces pombe) that has been phosphorylated at the positions equivalent to Ser-377, Ser-526, and Ser-698 of the amino acid sequence represented by UniProtKB:O13839. Example: UniProtKB:O13839, Ser-377/Ser-526/Ser-698, MOD:00046." [PRO:DAN, PomBase:VW, PMID:22684255]
comment: Category=organism-modification. Requested by=PomBase. Kinase=("sid2"; PR:000050482; Ser-377/Ser-526/Ser-698). Evidence=(ECO:0000006, based on PMID:22684255).
synonym: "Spom-fin1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O13839, Ser-377/Ser-526/Ser-698, MOD:00046" NARROW PRO-proteoform-std [PRO:DNx]
is_a: PR:000050480 ! G2-specific protein kinase fin1 (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
and you, thanks!
