### ISSUE TITLE
Term issue: rng2 phosphorylated

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#223]
O14188
rng2 - phosphorylated on S199 and S207
rng2 - unphosphorylated on S199 and S207
PMID:33131769

**Comment by nataled** [comment]
Hi Val,
Happy New Year! Here's your term:

PR:000050484 rng2/Phos(S199/S207)

[Term]
id: PR:000050484
name: Ras GTPase-activating-like protein rng2 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A Ras GTPase-activating-like protein rng2 (Schizosaccharomyces pombe) that has been phosphorylated at the positions equivalent to Ser-199 and Ser-207 of the amino acid sequence represented by UniProtKB:O14188. Example: UniProtKB:O14188, Ser-199/Ser-207, MOD:00046." [PRO:DAN, PomBase:VW, PMID:33131769]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-rng2/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O14188, Ser-199/Ser-207, MOD:00046" NARROW PRO-proteoform-std [PRO:DNx]
is_a: PR:000050483 ! Ras GTPase-activating-like protein rng2 (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by nataled** [comment]
The unphosphorylated version:

PR:000050485 rng2/UnPhos(S199/S207)

[Term]
id: PR:000050485
name: Ras GTPase-activating-like protein rng2 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A Ras GTPase-activating-like protein rng2 (Schizosaccharomyces pombe) that has not been phosphorylated at the positions equivalent to Ser-199 and Ser-207 of the amino acid sequence represented by UniProtKB:O14188. Example: UniProtKB:O14188, Ser-199/Ser-207, PR:000026291." [PRO:DAN, PomBase:VW, PMID:33131769]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-rng2/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O14188, Ser-199/Ser-207, PR:000026291" NARROW PRO-proteoform-std [PRO:DNx]
is_a: PR:000050483 ! Ras GTPase-activating-like protein rng2 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
Thanks! Happy New Year!
