### ISSUE TITLE
Term issue:  cdc15 unphosphorylated

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#224]
cdc15
unphosphorylated form

PMID:32101481 Bhattacharjee et al., 2020

Q09822

**Comment by nataled** [comment]
Hi Val,
Are there specific sites you want to assert as unphosphorylated, or all sites, or just those phosphorylated specifically by pom1?

**Comment by ValWood** [comment]
It could be the pom1 phosphorylated sites which at this point are known to be
S405, S511, S527, S605, S636, S702, S710, S721, S732, S743, S752, S774, S785, S786, S813, S821, S831, S836, S840 
 T419, T492

**Comment by nataled** [comment]
Hi Val,
Your term is below:

cdc15/UnPhos(S405/T419/T492/S511/S527/S605/S636/S702/S710/S721/S732/S743/S752/S774/S785/S786/S813/S821/S831/S836/S840)

[Term]
id: PR:000050489
name: cell division control protein 15 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A cell division control protein 15 (Schizosaccharomyces pombe) that has not been phosphorylated by pom1, at the positions equivalent to Ser-405, Thr-419, Thr-492, Ser-511, Ser-527, Ser-605, Ser-636, Ser-702, Ser-710, Ser-721, Ser-732, Ser-743, Ser-752, Ser-774, Ser-785, Ser-786, Ser-813, Ser-821, Ser-831, Ser-836, and Ser-840 of the amino acid sequence represented by UniProtKB:Q09822. Example: UniProtKB:Q09822, Ser-405/Thr-419/Thr-492/Ser-511/Ser-527/Ser-605/Ser-636/Ser-702/Ser-710/Ser-721/Ser-732/Ser-743/Ser-752/Ser-774/Ser-785/Ser-786/Ser-813/Ser-821/Ser-831/Ser-836/Ser-840, PR:000026291." [PRO:DAN, PomBase:VW, PMID:32101481]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-cdc15/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q09822, Ser-405/Thr-419/Thr-492/Ser-511/Ser-527/Ser-605/Ser-636/Ser-702/Ser-710/Ser-721/Ser-732/Ser-743/Ser-752/Ser-774/Ser-785/Ser-786/Ser-813/Ser-821/Ser-831/Ser-836/Ser-840, PR:000026291" NARROW PRO-proteoform-std [PRO:DNx]
is_a: PR:000050488 ! cell division control protein 15 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
