### ISSUE TITLE
Term issue: mid1 phosphorylated form

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#225]
mid1 P78953
modified residue S110, S127, S218, S227, S329, S432, S452, S464, S531 added by sid2 
during mitotic M phase

(Sid2 phosphorylates Mid1 to drive its removal from the cortex at CR constriction onset. )
PMID:30853434

Also a  unphosphorylated form for these residues

**Comment by nataled** [comment]
Hi Val,
Here are your terms:

Phosphorylated: PR:000050492 mid1/Phos(S110, S127, S218, S227, S329, S432, S452, S464, S531)
Unphosphorylated: PR:000050493 mid1/UnPhos(S110, S127, S218, S227, S329, S432, S452, S464, S531)

[Term]
id: PR:000050492
name: division mal foutue 1 protein phosphorylated 1 (Schizosaccharomyces pombe)
def: "A division mal foutue 1 protein (Schizosaccharomyces pombe) that has been phosphorylated at the positions equivalent to Ser-110, Ser-127, Ser-218, Ser-227, Ser-329, Ser-432, Ser-452, Ser-464, and Ser-531 of the amino acid sequence represented by UniProtKB:P78953. Example: UniProtKB:P78953, Ser-110/Ser-127/Ser-218/Ser-227/Ser-329/Ser-432/Ser-452/Ser-464/Ser-531, MOD:00046." [PRO:DAN, PomBase:VW, PMID:30853434]
comment: Category=organism-modification. Requested by=PomBase. Kinase=("sid2"; PR:000050490; Ser-110/Ser-127/Ser-218/Ser-227/Ser-329/Ser-432/Ser-452/Ser-464/Ser-531).
synonym: "Spom-mid1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:P78953, Ser-110/Ser-127/Ser-218/Ser-227/Ser-329/Ser-432/Ser-452/Ser-464/Ser-531, MOD:00046" NARROW PRO-proteoform-std [PRO:DNx]
is_a: PR:000050491 ! division mal foutue 1 protein (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050493
name: division mal foutue 1 protein phosphorylated 1 (Schizosaccharomyces pombe)
def: "A division mal foutue 1 protein (Schizosaccharomyces pombe) that has not been phosphorylated at the positions equivalent to Ser-110, Ser-127, Ser-218, Ser-227, Ser-329, Ser-432, Ser-452, Ser-464, and Ser-531 of the amino acid sequence represented by UniProtKB:P78953. Example: UniProtKB:P78953, Ser-110/Ser-127/Ser-218/Ser-227/Ser-329/Ser-432/Ser-452/Ser-464/Ser-531, PR:000026291." [PRO:DAN, PomBase:VW, PMID:30853434]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-mid1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:P78953, Ser-110/Ser-127/Ser-218/Ser-227/Ser-329/Ser-432/Ser-452/Ser-464/Ser-531, PR:000026291" NARROW PRO-proteoform-std [PRO:DNx]
is_a: PR:000050491 ! division mal foutue 1 protein (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
Hi Darren, 
Are the names automated  from Uniprot. I was confused when I saw "division mal foutue 1" because I have never seen Mid1 called this. I traced to a very early allele description. I'll ask UniProt to update the protein name today to "allinin-related medial ring protein". Will this  change filter through to PRO?
v

**Comment by ValWood** [comment]
Also PR:000050493 should **un**phosporylated.

**Comment by nataled** [comment]
Thanks for catching the typo. I had caught it as well, but only after I posted my reply. As for the name, consider it done. The UniProt name did look odd to me. I mean, for English. Turns out it is French, whose Google translation is...interesting. In any case, I've already made the change in PRO, and will upload after I attend to your next request.

**Comment by ValWood** [comment]
Yeah on the old paper and was Swiss-French, and  the Uniprot Fungal curators are too so they probably liked it ;)
