### ISSUE TITLE
Move PRO Wiki pages to PRO website

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#227]
The following pages need to be moved to the PRO website. Only the top page needs to be linked from the main PRO page, as all other links are from within the wiki. Indentations indicate that the indented page is linked from within the one-level-up page, and all links within that referring page must be updated accordingly.
<pre>
^ https://confluence.proteininformationresource.org/display/PROWIKI/Home (new location to be linked to "Wiki" on PRO header)
  ^ https://confluence.proteininformationresource.org/display/PROWIKI/Events
      https://confluence.proteininformationresource.org/display/PROWIKI/Protein+Ontology+(PRO)+workshop+2016
    ^ https://confluence.proteininformationresource.org/display/PROWIKI/Protein_Ontology_3ndAnnual_Meeting
          ALL PRESENTATIONS NEED TO BE MOVED AND LINKED
    ! https://confluence.proteininformationresource.org/display/PROWIKI/Protein_Ontology_2ndAnnual_Meeting
    ! https://confluence.proteininformationresource.org/display/PROWIKI/Protein_Ontology_Kick-Off_Meeting
  https://confluence.proteininformationresource.org/display/PROWIKI/Resources_Adopted_by_PRO
  https://confluence.proteininformationresource.org/display/PROWIKI/PRO+Citations
  https://confluence.proteininformationresource.org/display/PROWIKI/PRO+Ontology+Manual+Curation+Guideline  
  https://confluence.proteininformationresource.org/download/attachments/6324369/PROlogofinal300.png?version=1&modificationDate=1424702012000&api=v2
</pre>

Pages marked with a caret (^) require link updates to a location to be decided by informatics team.
Pages marked with an exclamation point (!) require link updates to files currently not found on any server.

**Comment by nataled** [comment]
Need to decide where to put these. Move to Documentation? Other? Keep it parallel to current site as it is now?
1) Can delete (from wiki) the curation manual

Goal is to have the move done by March 19th, but can extend through May if necessary.

**Comment by nataled** [comment]
To be discussed is the fate of the pages for Resources adopted by PRO and for PRO Citations. If these are removed, the page could reasonably be called "About PRO", and we would add links to Documentation and to Publications. The header on all pages would change so that 'Wiki', 'Documentation', and 'Publications' would be removed, replaced by 'About PRO', in the order:

PRO tracker     About PRO
RACE-PRO       PRO Consortium

**Comment by nataled** [comment]
Decision made after consortium teleconference: keep all pages.

**Comment by nataled** [comment]
New suggestion:
<pre>
Wiki                 ---->                  New Page to Link From
-------                                     -----
Events                                      Community
Resources Adopted by PRO                    Community
PRO Citations                               Community (change name of page to 'Citations to PRO')
PRO OBO Pre-Release Version                 Community
PRO Logo                                    Documentation?
</pre>
The new "Community" page is just the renamed Wiki page.

**Comment by nataled** [comment]
Changes needed to @jz26's wiki replacement:
1) Refresh contents with what is now in 'old' wiki
2) Remove left navigation panel
3) Remove table of contents (the list between "Welcome..." and "Events"
4) Move PRO logo to the existing 'Documentation' page.
5) Change the name 'Wiki' in PRO banner to 'Community' and link to the new wiki replacement page.

**Comment by jz26** [comment]
> The following pages need to be moved to the PRO website. Only the top page needs to be linked from the main PRO page, as all other links are from within the wiki. Indentations indicate that the indented page is linked from within the one-level-up page, and all links within that referring page must be updated accordingly.
> 
> ^ https://confluence.proteininformationresource.org/display/PROWIKI/Home (new location to be linked to "Wiki" on PRO header)
>   ^ https://confluence.proteininformationresource.org/display/PROWIKI/Events
>       https://confluence.proteininformationresource.org/display/PROWIKI/Protein+Ontology+(PRO)+workshop+2016
>     ^ https://confluence.proteininformationresource.org/display/PROWIKI/Protein_Ontology_3ndAnnual_Meeting
>           ALL PRESENTATIONS NEED TO BE MOVED AND LINKED
>     ! https://confluence.proteininformationresource.org/display/PROWIKI/Protein_Ontology_2ndAnnual_Meeting
>     ! https://confluence.proteininformationresource.org/display/PROWIKI/Protein_Ontology_Kick-Off_Meeting
>   https://confluence.proteininformationresource.org/display/PROWIKI/Resources_Adopted_by_PRO
>   https://confluence.proteininformationresource.org/display/PROWIKI/PRO+Citations
>   https://confluence.proteininformationresource.org/display/PROWIKI/PRO+Ontology+Manual+Curation+Guideline  
>   https://confluence.proteininformationresource.org/download/attachments/6324369/PROlogofinal300.png?version=1&modificationDate=1424702012000&api=v2
> Pages marked with a caret (^) require link updates to a location to be decided by informatics team.
> Pages marked with an exclamation point (!) require link updates to files currently not found on any server.

done

**Comment by jz26** [comment]
done

**Comment by jz26** [comment]
done
