### ISSUE TITLE
Term issue: Dis2 modified form

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#233]
dis2 T319
P13681
modified residue T316 added by cdc2 added during mitotic metaphase | IDA | Yamano H et al. (1994)
modified residue T316 added by cdk9 | IDA | Parua PK et al. (2018)

**Comment by nataled** [comment]
Hi Val,

I'm assuming that 'T319' is a typo? If so, your requested term is:

PR:000050483:      dis2/Phos(T316)

[Term]
id: PR:000050483
name: serine/threonine-protein phosphatase PP1-1 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A serine/threonine-protein phosphatase PP1-1 (Schizosaccharomyces pombe) that has been phosphorylated at the position equivalent to Thr-316 of the amino acid sequence represented by UniProtKB:P13681. Example: UniProtKB:P13681, Thr-316, MOD:00047." [PRO:DAN, PomBase:VW, PMID:29899453, PMID:7957097]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-dis2/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:P13681, Thr-316, MOD:00047" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050482 ! serine/threonine-protein phosphatase PP1-1 (Schizosaccharomyces pombe)
relationship: has_part MOD:00047 ! O-phospho-L-threonine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
Thanks for correctly interpreting!

**Comment by ValWood** [comment]
OK, for this one I actually needed the unphosphorylated T316 (this is the active from that dephosphorylates Spt5

**Comment by ValWood** [comment]
I see I am not allowed to re-open. I'll transfer to a new ticket.

**Comment by nataled** [comment]
No need to worry about re-opening, as comments on closed tickets works just fine. In any case, since you already opened a new ticket, I'll re-close this one and handle things there.
