### ISSUE TITLE
GTP bound forms?

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#236]
Hi @nataled  

Does PRO handle these?

Best,

Val

**Comment by nataled** [comment]
Yes. We currently have the following S. pombe GTP-bound forms:

PR:000036979 ras1
PR:000044799 cdc42
PR:000045538 spi1
PR:000050473 rho1
PR:000050251 rho2
PR:000037031 rho3

In addition we have a GDP-bound form for spi1, PR:000045536.

**Comment by ValWood** [comment]
I wanted one for spg1  P87027 PMID:9420333

**Comment by nataled** [comment]
Your term:

spg1/GTP+

[Term]
id: PR:000050507
name: septum-promoting GTP-binding protein 1, GTP-bound form (Schizosaccharomyces pombe)
def: "A septum-promoting GTP-binding protein 1 (Schizosaccharomyces pombe) that is non-covalently bound to GTP." [PRO:DAN, PomBase:VW, PMID:9420333]
comment: Category=organism-complex. Requested by=PomBase.
synonym: "Spom-spg1/GTP+" EXACT PRO-short-label [PRO:DAN]
intersection_of: PR:000050506 ! septum-promoting GTP-binding protein 1 (Schizosaccharomyces pombe)
intersection_of: non-covalently_bound_to CHEBI:15996 ! GTP
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
