### ISSUE TITLE
OK, for this one I actually needed the unphosphorylated T316 (this is the active from that dephosphorylates Spt5

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#237]
OK, for this one I actually needed the unphosphorylated T316 (this is the active from that dephosphorylates Spt5

_Originally posted by @ValWood in https://github.com/PROconsortium/PRoteinOntology/issues/233#issuecomment-827776631_

**Comment by ValWood** [comment]
Dis2  unphosphorylated T316 (this is the active from that dephosphorylates Spt5

**Comment by ValWood** [comment]
P13681

**Comment by nataled** [comment]
Your term:

PR:000050599  dis2/UnPhos(T316)

[Term]
id: PR:000050599
name: serine/threonine-protein phosphatase PP1-1 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A serine/threonine-protein phosphatase PP1-1 (Schizosaccharomyces pombe) that has not been phosphorylated at the position equivalent to Thr-316 of the amino acid sequence represented by UniProtKB:P13681. Example: UniProtKB:P13681, Thr-316, PR:000026291." [PRO:DAN, PomBase:VW, PMID:29899453, PMID:7957097]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-dis2/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:P13681, Thr-316, PR:000026291" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050482 ! serine/threonine-protein phosphatase PP1-1 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
