### ISSUE TITLE
Term issue: AMPK (Ssp2) phosphorylated form

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#240]
Ssp2 O74536 (Thr189)
and unphosphorylated form.

PMID:22375066

**Comment by nataled** [comment]
Here you go, Val!

PR:000050517 ssp2/Phos:(T189)
PR:000050518 ssp2/UnPhos:(T189)

[Term]
id: PR:000050517
name: SNF1-like protein kinase ssp2 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A SNF1-like protein kinase ssp2 (Schizosaccharomyces pombe) that has been phosphorylated at the position equivalent to Thr-189 of the amino acid sequence represented by UniProtKB:O74536. Example: UniProtKB:O74536, Thr-189, MOD:00047." [PRO:DAN, PomBase:VW, PMID:22375066]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-ssp2/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O74536, Thr-189, MOD:00047" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050516 ! SNF1-like protein kinase ssp2 (Schizosaccharomyces pombe)
relationship: has_part MOD:00047 ! O-phospho-L-threonine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050518
name: SNF1-like protein kinase ssp2 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A SNF1-like protein kinase ssp2 (Schizosaccharomyces pombe) that has not been phosphorylated at the position equivalent to Thr-189 of the amino acid sequence represented by UniProtKB:O74536. Example: UniProtKB:O74536, Thr-189, MOD:00047." [PRO:DAN, PomBase:VW, PMID:22375066]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-ssp2/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O74536, Thr-189, PR:000026291" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050516 ! SNF1-like protein kinase ssp2 (Schizosaccharomyces pombe)
relationship: has_part MOD:00047 ! O-phospho-L-threonine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
