### ISSUE TITLE
NTR Scr1 phosphorylated/ unphosphorylated

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#241]
scr1
S235A, S332A, S333A, S408A, S410A
PMID:22140232
O14335

**Comment by nataled** [comment]
Hi Val, your terms are here!

PR:000050520 scr1/Phos:(S235/S332/S333/S408/S410)
PR:000050521 scr1/UnPhos:(S235/S332/S333/S408/S410)

Question: is ECO:0005528 (site-directed mutagenesis phenotypic evidence)the right code for this? I'd like to start using something more specific than just "experimental". To that end, if you happen to know the correct code for each of the requests you make, please also include that information in future requests. Thanks!

[Term]
id: PR:000050520
name: DNA-binding protein scr1 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A DNA-binding protein scr1 (Schizosaccharomyces pombe) that has been phosphorylated at positions equivalent to Ser-235, Ser-332, Ser-333, Ser-408, and Ser-410 of the amino acid sequence represented by UniProtKB:O14335. Example: UniProtKB:O14335, Ser-235/Ser-332/Ser-333/Ser-408/Ser-410, MOD:00046." [PRO:DAN, PomBase:VW, PMID:22140232]
comment: Category=organism-modification. Requested by=PomBase. Kinase=("ssp2"; PR:000050522; Ser-235/Ser-332/Ser-333/Ser-408/Ser-410). Evidence=(ECO:0000006, based on PMID:22140232).
synonym: "Spom-scr1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O14335, Ser-235/Ser-332/Ser-333/Ser-408/Ser-410, MOD:00046" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050519 ! DNA-binding protein scr1 (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050521
name: DNA-binding protein scr1 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A DNA-binding protein scr1 (Schizosaccharomyces pombe) that has not been phosphorylated at positions equivalent to Ser-235, Ser-332, Ser-333, Ser-408, and Ser-410 of the amino acid sequence represented by UniProtKB:O14335. Example: UniProtKB:O14335, Ser-235/Ser-332/Ser-333/Ser-408/Ser-410, PR:000026291." [PRO:DAN, PomBase:VW, PMID:22140232]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-scr1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O14335, Ser-235/Ser-332/Ser-333/Ser-408/Ser-410, PR:000026291" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050519 ! DNA-binding protein scr1 (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
site-directed mutagenesis phenotypic evidence
sounds good!

will suggest evidence codes.
