### ISSUE TITLE
Term issue: NTR 

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#242]
Q9HDZ6
dam1 | MOD:00046 | O-phospho-L-serine | IDA | residue S143 , added_by plo1
PMID:22375062

**Comment by nataled** [comment]
Hi Val, here is your term (with no errors!). Thanks for providing the evidence code! Did you want the unphosphorylated version as well?

PR:000050524 dam1/Phos:(S143)

[Term]
id: PR:000050524
name: DASH complex subunit dam1 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A DASH complex subunit dam1 (Schizosaccharomyces pombe) that has been phosphorylated at the position equivalent to Ser-143 of the amino acid sequence represented by UniProtKB:Q9HDZ6. Example: UniProtKB:Q9HDZ6, Ser-143, MOD:00046." [PRO:DAN, PomBase:VW, PMID:22375062]
comment: Category=organism-modification. Requested by=PomBase. Kinase=("plo1"; PR:000050505; Ser-143). Evidence=(ECO:0000314, based on PMID:22375062).
synonym: "Spom-dam1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q9HDZ6, Ser-143, MOD:00046" NARROW PRO-proteoform-std [PRO:DNx]
is_a: PR:000050523 ! DASH complex subunit dam1 (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
Just the -P form for now
