### ISSUE TITLE
Term issue: Histone H4

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#245]
PMID:22150589

P09322  hhf1  H4-K20-Me + H4-K20me3
 hhf2 H4-K20-Me + H4-K20me3
hhf3 H4-K20-Me + H4-K20me3

(I see they all map to the same UniProt ID, I thought these had been split out?)

**Comment by nataled** [comment]
Hi Val,
Unfortunately I don't have access to the full text so I can't check this myself, but when you say "H4-K20-Me" is that supposed to be monomethylated? In the abstract I see reference to only di- and tri-methylated K20.

As for splitting out, this is an ongoing process in UniProtKB. Unsure if the scope of that includes S. pombe. In any case, it makes no real difference for PRO.

**Comment by nataled** [comment]
Correction: I do see reference to "all three states". So that raises the question of whether or not you want all three, for all three genes.

**Comment by ValWood** [comment]
Let's have all 3.  We will need them because the histone readers are specific.

**Comment by nataled** [comment]
Here are your terms:

PR:000050529 hhf1/Me1:(K20)
PR:000050530 hhf1/Me2:(K20)
PR:000050531 hhf1/Me3:(K20)
PR:000050532 hhf2/Me1:(K20)
PR:000050533 hhf2/Me2:(K20)
PR:000050534 hhf2/Me3:(K20)
PR:000050535 hhf3/Me1:(K20)
PR:000050536 hhf3/Me2:(K20)
PR:000050537 hhf3/Me3:(K20)

[Term]
id: PR:000050529
name: histone H4, hhf1 gene translation product, initiator methionine removed monomethylated 1 (Schizosaccharomyces pombe)
def: "A histone H4, hhf1 gene translation product (Schizosaccharomyces pombe) that has had the initiator methionine removed and that has been monomethylated at the position equivalent to Lys-21 of the amino acid sequence represented by UniProtKB:P09322. UniProtKB:P09322, 2-103, Lys-21, MOD:00085." [PRO:DAN, PomBase:VW, PMID:22150589]
comment: Category=organism-modification. Requested by=PomBase. Note: Residue numbering for histones typically account for intiiator methionine removal. Hence, Lys-21 of the full sequence as presented in UniProtKB:P09322 is called K20 in the literature.
synonym: "Spom-hhf1/InitMet-/Me1:1" EXACT PRO-short-label [PRO:DAN]
synonym: "histone H4 hhf1 K20me1 (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
synonym: "histone H4 K20me1 (Schizosaccharomyces pombe)" BROAD [PRO:DAN]
synonym: "PRO_0000158357, Lys-21, MOD:00085" BROAD PRO-proteoform-ftid [PRO:DAN]
synonym: "UniProtKB:P09322, 2-103, Lys-21, MOD:00085" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:000050526 ! histone H4, hhf1 gene translation product (Schizosaccharomyces pombe)
relationship: has_part MOD:00085 ! N6-dimethyl-L-lysine
relationship: lacks_part PR:000021937 ! initiator methionine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050530
name: histone H4, hhf1 gene translation product, initiator methionine removed dimethylated 1 (Schizosaccharomyces pombe)
def: "A histone H4, hhf1 gene translation product (Schizosaccharomyces pombe) that has had the initiator methionine removed and that has been dimethylated at the position equivalent to Lys-21 of the amino acid sequence represented by UniProtKB:P09322. UniProtKB:P09322, 2-103, Lys-21, MOD:00084." [PRO:DAN, PomBase:VW, PMID:22150589]
comment: Category=organism-modification. Requested by=PomBase. Note: Residue numbering for histones typically account for intiiator methionine removal. Hence, Lys-21 of the full sequence as presented in UniProtKB:P09322 is called K20 in the literature.
synonym: "Spom-hhf1/InitMet-/Me2:1" EXACT PRO-short-label [PRO:DAN]
synonym: "histone H4 hhf1 K20me2 (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
synonym: "histone H4 K20me2 (Schizosaccharomyces pombe)" BROAD [PRO:DAN]
synonym: "PRO_0000158357, Lys-21, MOD:00084" BROAD PRO-proteoform-ftid [PRO:DAN]
synonym: "UniProtKB:P09322, 2-103, Lys-21, MOD:00084" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:000050526 ! histone H4, hhf1 gene translation product (Schizosaccharomyces pombe)
relationship: has_part MOD:00084 ! N6,N6-dimethyl-L-lysine
relationship: lacks_part PR:000021937 ! initiator methionine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050531
name: histone H4, hhf1 gene translation product, initiator methionine removed trimethylated 1 (Schizosaccharomyces pombe)
def: "A histone H4, hhf1 gene translation product (Schizosaccharomyces pombe) that has had the initiator methionine removed and that has been trimethylated at the position equivalent to Lys-21 of the amino acid sequence represented by UniProtKB:P09322. UniProtKB:P09322, 2-103, Lys-21, MOD:00083." [PRO:DAN, PomBase:VW, PMID:22150589]
comment: Category=organism-modification. Requested by=PomBase. Note: Residue numbering for histones typically account for intiiator methionine removal. Hence, Lys-21 of the full sequence as presented in UniProtKB:P09322 is called K20 in the literature.
synonym: "Spom-hhf1/InitMet-/Me3:1" EXACT PRO-short-label [PRO:DAN]
synonym: "histone H4 hhf1 K20me3 (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
synonym: "histone H4 K20me3 (Schizosaccharomyces pombe)" BROAD [PRO:DAN]
synonym: "PRO_0000158357, Lys-21, MOD:00083" BROAD PRO-proteoform-ftid [PRO:DAN]
synonym: "UniProtKB:P09322, 2-103, Lys-21, MOD:00083" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:000050526 ! histone H4, hhf1 gene translation product (Schizosaccharomyces pombe)
relationship: has_part MOD:00083 ! N6,N6,N6-dimethyl-L-lysine
relationship: lacks_part PR:000021937 ! initiator methionine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050532
name: histone H4, hhf2 gene translation product, initiator methionine removed monomethylated 1 (Schizosaccharomyces pombe)
def: "A histone H4, hhf2 gene translation product (Schizosaccharomyces pombe) that has had the initiator methionine removed and that has been monomethylated at the position equivalent to Lys-21 of the amino acid sequence represented by UniProtKB:P09322. UniProtKB:P09322, 2-103, Lys-21, MOD:00085." [PRO:DAN, PomBase:VW, PMID:22150589]
comment: Category=organism-modification. Requested by=PomBase. Note: Residue numbering for histones typically account for intiiator methionine removal. Hence, Lys-21 of the full sequence as presented in UniProtKB:P09322 is called K20 in the literature.
synonym: "Spom-hhf2/InitMet-/Me1:1" EXACT PRO-short-label [PRO:DAN]
synonym: "histone H4 hhf2 K20me1 (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
synonym: "histone H4 K20me1 (Schizosaccharomyces pombe)" BROAD [PRO:DAN]
synonym: "PRO_0000158357, Lys-21, MOD:00085" BROAD PRO-proteoform-ftid [PRO:DAN]
synonym: "UniProtKB:P09322, 2-103, Lys-21, MOD:00085" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:000050527 ! histone H4, hhf2 gene translation product (Schizosaccharomyces pombe)
relationship: has_part MOD:00085 ! N6-dimethyl-L-lysine
relationship: lacks_part PR:000021937 ! initiator methionine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050533
name: histone H4, hhf2 gene translation product, initiator methionine removed dimethylated 1 (Schizosaccharomyces pombe)
def: "A histone H4, hhf2 gene translation product (Schizosaccharomyces pombe) that has had the initiator methionine removed and that has been dimethylated at the position equivalent to Lys-21 of the amino acid sequence represented by UniProtKB:P09322. UniProtKB:P09322, 2-103, Lys-21, MOD:00084." [PRO:DAN, PomBase:VW, PMID:22150589]
comment: Category=organism-modification. Requested by=PomBase. Note: Residue numbering for histones typically account for intiiator methionine removal. Hence, Lys-21 of the full sequence as presented in UniProtKB:P09322 is called K20 in the literature.
synonym: "Spom-hhf2/InitMet-/Me2:1" EXACT PRO-short-label [PRO:DAN]
synonym: "histone H4 hhf2 K20me2 (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
synonym: "histone H4 K20me2 (Schizosaccharomyces pombe)" BROAD [PRO:DAN]
synonym: "PRO_0000158357, Lys-21, MOD:00084" BROAD PRO-proteoform-ftid [PRO:DAN]
synonym: "UniProtKB:P09322, 2-103, Lys-21, MOD:00084" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:000050527 ! histone H4, hhf2 gene translation product (Schizosaccharomyces pombe)
relationship: has_part MOD:00084 ! N6,N6-dimethyl-L-lysine
relationship: lacks_part PR:000021937 ! initiator methionine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050534
name: histone H4, hhf2 gene translation product, initiator methionine removed trimethylated 1 (Schizosaccharomyces pombe)
def: "A histone H4, hhf2 gene translation product (Schizosaccharomyces pombe) that has had the initiator methionine removed and that has been trimethylated at the position equivalent to Lys-21 of the amino acid sequence represented by UniProtKB:P09322. UniProtKB:P09322, 2-103, Lys-21, MOD:00083." [PRO:DAN, PomBase:VW, PMID:22150589]
comment: Category=organism-modification. Requested by=PomBase. Note: Residue numbering for histones typically account for intiiator methionine removal. Hence, Lys-21 of the full sequence as presented in UniProtKB:P09322 is called K20 in the literature.
synonym: "Spom-hhf2/InitMet-/Me3:1" EXACT PRO-short-label [PRO:DAN]
synonym: "histone H4 hhf2 K20me3 (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
synonym: "histone H4 K20me3 (Schizosaccharomyces pombe)" BROAD [PRO:DAN]
synonym: "PRO_0000158357, Lys-21, MOD:00083" BROAD PRO-proteoform-ftid [PRO:DAN]
synonym: "UniProtKB:P09322, 2-103, Lys-21, MOD:00083" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:000050527 ! histone H4, hhf2 gene translation product (Schizosaccharomyces pombe)
relationship: has_part MOD:00083 ! N6,N6,N6-dimethyl-L-lysine
relationship: lacks_part PR:000021937 ! initiator methionine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050535
name: histone H4, hhf3 gene translation product, initiator methionine removed monomethylated 1 (Schizosaccharomyces pombe)
def: "A histone H4, hhf3 gene translation product (Schizosaccharomyces pombe) that has had the initiator methionine removed and that has been monomethylated at the position equivalent to Lys-21 of the amino acid sequence represented by UniProtKB:P09322. UniProtKB:P09322, 2-103, Lys-21, MOD:00085." [PRO:DAN, PomBase:VW, PMID:22150589]
comment: Category=organism-modification. Requested by=PomBase. Note: Residue numbering for histones typically account for intiiator methionine removal. Hence, Lys-21 of the full sequence as presented in UniProtKB:P09322 is called K20 in the literature.
synonym: "Spom-hhf3/InitMet-/Me1:1" EXACT PRO-short-label [PRO:DAN]
synonym: "histone H4 hhf3 K20me1 (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
synonym: "histone H4 K20me1 (Schizosaccharomyces pombe)" BROAD [PRO:DAN]
synonym: "PRO_0000158357, Lys-21, MOD:00085" BROAD PRO-proteoform-ftid [PRO:DAN]
synonym: "UniProtKB:P09322, 2-103, Lys-21, MOD:00085" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:000050528 ! histone H4, hhf3 gene translation product (Schizosaccharomyces pombe)
relationship: has_part MOD:00085 ! N6-dimethyl-L-lysine
relationship: lacks_part PR:000021937 ! initiator methionine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050536
name: histone H4, hhf3 gene translation product, initiator methionine removed dimethylated 1 (Schizosaccharomyces pombe)
def: "A histone H4, hhf3 gene translation product (Schizosaccharomyces pombe) that has had the initiator methionine removed and that has been dimethylated at the position equivalent to Lys-21 of the amino acid sequence represented by UniProtKB:P09322. UniProtKB:P09322, 2-103, Lys-21, MOD:00084." [PRO:DAN, PomBase:VW, PMID:22150589]
comment: Category=organism-modification. Requested by=PomBase. Note: Residue numbering for histones typically account for intiiator methionine removal. Hence, Lys-21 of the full sequence as presented in UniProtKB:P09322 is called K20 in the literature.
synonym: "Spom-hhf3/InitMet-/Me2:1" EXACT PRO-short-label [PRO:DAN]
synonym: "histone H4 hhf3 K20me2 (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
synonym: "histone H4 K20me2 (Schizosaccharomyces pombe)" BROAD [PRO:DAN]
synonym: "PRO_0000158357, Lys-21, MOD:00084" BROAD PRO-proteoform-ftid [PRO:DAN]
synonym: "UniProtKB:P09322, 2-103, Lys-21, MOD:00084" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:000050528 ! histone H4, hhf3 gene translation product (Schizosaccharomyces pombe)
relationship: has_part MOD:00084 ! N6,N6-dimethyl-L-lysine
relationship: lacks_part PR:000021937 ! initiator methionine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050537
name: histone H4, hhf3 gene translation product, initiator methionine removed trimethylated 1 (Schizosaccharomyces pombe)
def: "A histone H4, hhf3 gene translation product (Schizosaccharomyces pombe) that has had the initiator methionine removed and that has been trimethylated at the position equivalent to Lys-21 of the amino acid sequence represented by UniProtKB:P09322. UniProtKB:P09322, 2-103, Lys-21, MOD:00083." [PRO:DAN, PomBase:VW, PMID:22150589]
comment: Category=organism-modification. Requested by=PomBase. Note: Residue numbering for histones typically account for intiiator methionine removal. Hence, Lys-21 of the full sequence as presented in UniProtKB:P09322 is called K20 in the literature.
synonym: "Spom-hhf3/InitMet-/Me3:1" EXACT PRO-short-label [PRO:DAN]
synonym: "histone H4 hhf3 K20me3 (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
synonym: "histone H4 K20me3 (Schizosaccharomyces pombe)" BROAD [PRO:DAN]
synonym: "PRO_0000158357, Lys-21, MOD:00083" BROAD PRO-proteoform-ftid [PRO:DAN]
synonym: "UniProtKB:P09322, 2-103, Lys-21, MOD:00083" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:000050528 ! histone H4, hhf3 gene translation product (Schizosaccharomyces pombe)
relationship: has_part MOD:00083 ! N6,N6,N6-dimethyl-L-lysine
relationship: lacks_part PR:000021937 ! initiator methionine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
