### ISSUE TITLE
Multiple PRO-proteoform-std 

### ISSUE THREAD

**Issue by Julie-Cowart** [PROconsortium/PRoteinOntology#247]
There is a recent 'change' with respect to PRO-proteoform-std lines, and that is that there can be multiple lines. I had been using those as a way to detect already-existing terms, but it failed because, for example, I'd have the proteoform in PRO defined with respect to some isoform but search with the canonical. To resolve that issue, I sometimes added both types of lines (one referencing the main identifier and and one referencing the canonical isoform):
synonym: "UniProtKB:P07492, 24-148" EXACT PRO-proteoform-std [PRO:DAN]
synonym: "UniProtKB:P07492-1, 24-148" NARROW PRO-proteoform-std [PRO:DAN]

We need to display all PRO-proteoform-std lines and also include the NARROW and EXACT clarifications (or maybe EXACT is implied unless it says narrow.

This issue was originally brought up in #216.

**Comment by nataled** [comment]
From the issue that I nearly just created. Take no action until discussed:

For terms that have multiple PRO-proteoform-std lines (and PRO-proteoform-ftid lines), it isn't clear which are EXACT and which are NARROW (or, potentially, RELATED and BROAD).

An example: https://proconsortium.org/app/entry/PR%3A000050508/
This shows:
<pre>
<b>PRO-proteoform-std:</b> UniProtKB:P10636, Ser-713, PR:000026291; UniProtKB:P10636-1, Ser-713, PR:000026291; UniProtKB:P10636-8, Ser-396, PR:000026291
</pre>

(the first one is EXACT, the others are NARROW)

We should indicate which are which. The possibilities for this are:
1) Append the appropriate tag to the indicated synonym, for example:
<pre>
<b>PRO-proteoform-std:</b> UniProtKB:P10636, Ser-713, PR:000026291 (EXACT); UniProtKB:P10636-1, Ser-713, PR:000026291 (NARROW); UniProtKB:P10636-8, Ser-396, PR:000026291 (NARROW)
</pre>
2) Split the possibilities into their own section (like is done for PRO-short-label, Gene-based, EXACT, etc).
<pre>
<b>PRO-proteoform-std EXACT:</b> UniProtKB:P10636, Ser-713, PR:000026291
<b>PRO-proteoform-std NARROW:</b> UniProtKB:P10636-1, Ser-713, PR:000026291; UniProtKB:P10636-8, Ser-396, PR:000026291
</pre>

I personally favor the first method, but with the addition of bold lettering for the synonym scope, like:
<pre>
<b>PRO-proteoform-std:</b> UniProtKB:P10636, Ser-713, PR:000026291 (<b>EXACT</b>); UniProtKB:P10636-1, Ser-713, PR:000026291 (<b>NARROW</b>); UniProtKB:P10636-8, Ser-396, PR:000026291 (<b>NARROW</b>)
</pre>

Generalizing this, the treatment should be done for any defined synonym type (these things: 'PRO-short-label', 'PRO-proteoform-std', etc). At the moment, there would be only two exceptions:
(1) PRO-short-label - these aren't always EXACT (we have a single example that is not) but there will always only be a single synonym of this type, so no need to distinguish.
(2) Gene-based - Though there are multiples of these, they are *never* EXACT.

**Comment by nataled** [comment]
Terminology:
"Types" = PRO-short-label, Gene-based, PRO-proteoform-std, PRO-proteoform-ftid
"Scopes" = EXACT, RELATED, NARROW, BROAD

Decision:
1) The format we will use for PRO-proteoform-std will be as given above except with scope in square brackets:<pre>
PRO-proteoform-std: UniProtKB:P10636, Ser-713, PR:000026291 [**EXACT**]; UniProtKB:P10636-1, Ser-713, PR:000026291 [**NARROW**]; UniProtKB:P10636-8, Ser-396, PR:000026291 [**NARROW**]</pre>

2) We will generalize the above to apply to all synonyms. Currently non-typed synonyms are listed under the relevant scope, so all EXACT or RELATED (etc) synonyms are listed like so:

EXACT: syn1; syn2
RELATED: syn3; syn4

Instead, these will be listed like so:

Other: syn1 [**EXACT**]; syn2 [**EXACT**]; syn3 [**RELATED**]; syn4 [**RELATED**]

3) Order of precedence will be first based on type, then on scope:
PRO-short-label: label [**SCOPE**]
Gene-based: syn1 [**RELATED**]; syn2 [**NARROW**]; syn3 [**BROAD**]
PRO-proteoform-std: syn4 [**EXACT**]; syn5 [**RELATED**]; syn6 [**NARROW**]; syn7 [**BROAD**]
PRO-proteoform-ftid: syn4 [**EXACT**]; syn5 [**RELATED**]; syn6 [**NARROW**]; syn7 [**BROAD**]
Other: syn8  [**EXACT**]; syn9 [**RELATED**]; syn10 [**NARROW**]; syn11 [**BROAD**]

Note that there will always be only a single PRO-short-label.
Note the Gene-based will never be EXACT.
"Other" refers to those synonyms that do not have a type indicated.

I suggest just treating all as if they all can have any scope.

**Comment by Julie-Cowart** [comment]
This above discussed solution for how we label all synonyms is updated on test. The ordering is hard coded and any new labels (besides PRO-short-label, Gene-based, PRO-proteoform-std, and PRO-proteoform-ftid) will appear just above Other but in indeterminant order so new labels will need to be added to the code explicitly.

For reference, here are some use cases that show the ordering (of types and scopes)
all 4 scopes of other - PR:000022979
gene based and 3 scopes of other - PR:000005265
gene based, PRO-proteoform-ftid, and other, PR:P0DTD2
PRO-proteoform-ftid and PRO-proteoform-std - PR:000046426

**Comment by karenross** [comment]
Here are three versions of the synonym view for PR:000022979 (see zip file):
1. PR_000022979-italics.html: same as Julie's version except bold scopes changed to italics
2. PR_000022979-grouped.html: each scope is listed once followed by all synonyms of that scope
3. PR_000022979-grouped-italics.html: same as 2 except bold scopes changed to italics
[synonym_views.zip](https://github.com/PROconsortium/PRoteinOntology/files/6909333/synonym_views.zip)

**Comment by nataled** [comment]
FINAL DECISION: use pipes.

This can go live publicly.

**Comment by Julie-Cowart** [comment]
Done and pushed to production
