### ISSUE TITLE
Term issue: NTR for Gtr1 and Gtr2 GTPases

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#253]
Hi,

Please could I get terms for the GDP and GTP bound forms of gtr1 and gtr2 (I don't know precise residues)

O74824 Gtr1
O74544 Gtr2

It seems that both forms have a role and the GDP bound form has an active role in the negative regulation. of TORC1 signalling because the deletion phenocopies the upstream GAP.

Note to self, required for
https://www.pombase.org/reference/PMID:33534698
https://www.pombase.org/reference/PMID:27227887

**Comment by nataled** [comment]
Hi Val,

Here are your terms:

PR:000050542 = Spom-gtr1/GDP+
PR:000050543 = Spom-gtr1/GTP+
PR:000050545 = Spom-gtr2/GDP+
PR:000050546 = Spom-gtr2/GTP+

<pre>[Term]
id: PR:000050542
name: GTP-binding protein gtr1, GDP-bound form (Schizosaccharomyces pombe)
def: "A GTP-binding protein gtr1 (Schizosaccharomyces pombe) that is non-covalently bound to GDP." [PRO:DAN, PomBase:VW, PMID:27227887, PMID:33534698]
comment: Category=organism-complex. Requested by=PomBase.
synonym: "Spom-gtr1/GDP+" EXACT PRO-short-label [PRO:DAN]
intersection_of: PR:000050541 ! GTP-binding protein gtr1 (Schizosaccharomyces pombe)
intersection_of: non-covalently_bound_to CHEBI:17552 ! GDP
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050543
name: GTP-binding protein gtr1, GTP-bound form (Schizosaccharomyces pombe)
def: "A GTP-binding protein gtr1 (Schizosaccharomyces pombe) that is non-covalently bound to GTP." [PPRO:DAN, PomBase:VW, PMID:27227887, PMID:33534698]
comment: Category=organism-complex. Requested by=PomBase.
synonym: "Spom-gtr1/GTP+" EXACT PRO-short-label [PRO:DAN]
intersection_of: PR:000050541 ! GTP-binding protein gtr1 (Schizosaccharomyces pombe)
intersection_of: non-covalently_bound_to CHEBI:15996 ! GTP
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050545
name: GTP-binding protein gtr2, GDP-bound form (Schizosaccharomyces pombe)
def: "A GTP-binding protein gtr2 (Schizosaccharomyces pombe) that is non-covalently bound to GDP." [PRO:DAN, PomBase:VW, PMID:27227887]
comment: Category=organism-complex. Requested by=PomBase.
synonym: "Spom-gtr2/GDP+" EXACT PRO-short-label [PRO:DAN]
intersection_of: PR:000050544 ! GTP-binding protein gtr2 (Schizosaccharomyces pombe)
intersection_of: non-covalently_bound_to CHEBI:17552 ! GDP
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050546
name: GTP-binding protein gtr2, GTP-bound form (Schizosaccharomyces pombe)
def: "A GTP-binding protein gtr2 (Schizosaccharomyces pombe) that is non-covalently bound to GTP." [PPRO:DAN, PomBase:VW, PMID:27227887]
comment: Category=organism-complex. Requested by=PomBase.
synonym: "Spom-gtr2/GTP+" EXACT PRO-short-label [PRO:DAN]
intersection_of: PR:000050544 ! GTP-binding protein gtr2 (Schizosaccharomyces pombe)
intersection_of: non-covalently_bound_to CHEBI:15996 ! GTP
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
