### ISSUE TITLE
Term issue:  pxl1 new terms

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#254]
pxl1 SPBC4F6.12
O74398

unphosphorylated, and phosphorylated on Cdk1 sites:
modified residue S3, S24, S31, T55, T64, S67, S97, S136, T214 
added by Cdc2(cdk1)

PMID:34133210

**Comment by nataled** [comment]
Hi Val,
Your terms are below:

Phosphorylated:       PR:000050548   pxl1/Phos:(S3/S24/S31/T55/T64/S67/S97/S136/T214)
Unphosphorylated:  PR:000050549   pxl1/UnPhos:(S3/S24/S31/T55/T64/S67/S97/S136/T214)

[Term]
id: PR:000050548
name: LIM domain-containing protein C4F6.12 phosphorylated 1 (Schizosaccharomyces pombe)
def: "A LIM domain-containing protein C4F6.12 (Schizosaccharomyces pombe) that has been phosphorylated at positions equivalent to Ser-3, Ser-24, Ser-31, Thr-55, Thr-64, Ser-67, Ser-97, Ser-136, and Thr-214 of the amino acid sequence represented by UniProtKB:O74398. Example: UniProtKB:O74398, Ser-3/Ser-24/Ser-31/Ser-67/Ser-97/Ser-136, MOD:00046|Thr-55/Thr-64/Thr-214, MOD:00047." [PRO:DAN, PomBase:VW, PMID:34133210]
comment: Category=organism-modification. Requested by=PomBase. Kinase=("cdc2"; PR:000036301; Ser-3/Ser-24/Ser-31/Thr-55/Thr-64/Ser-67/Ser-97/Ser-136/Thr-214). Evidence=(ECO:0000006, based on PMID:34133210).
synonym: "Spom-pxl1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O74398, Ser-3/Ser-24/Ser-31/Ser-67/Ser-97/Ser-136, MOD:00046|Thr-55/Thr-64/Thr-214, MOD:00047" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050547 ! LIM domain-containing protein C4F6.12 (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: has_part MOD:00047 ! O-phospho-L-threonine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

[Term]
id: PR:000050549
name: LIM domain-containing protein C4F6.12 unphosphorylated 1 (Schizosaccharomyces pombe)
def: "A LIM domain-containing protein C4F6.12 (Schizosaccharomyces pombe) that has not been phosphorylated at positions equivalent to Ser-3, Ser-24, Ser-31, Thr-55, Thr-64, Ser-67, Ser-97, Ser-136, and Thr-214 of the amino acid sequence represented by UniProtKB:O74398. Example: UniProtKB:O74398, Ser-3/Ser-24/Ser-31/Thr-55/Thr-64/Ser-67/Ser-97/Ser-136/Thr-214, PR:000026291." [PRO:DAN, PomBase:VW, PMID:34133210]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-pxl1/UnPhos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O74398, Ser-3/Ser-24/Ser-31/Thr-55/Thr-64/Ser-67/Ser-97/Ser-136/Thr-214, PR:000026291" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000050547 ! LIM domain-containing protein C4F6.12 (Schizosaccharomyces pombe)
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
