### ISSUE TITLE
tif211 Term issue: 

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#258]
P56286

please add Ser52 phosphorylated form PMID:28771613
added by gcn2

tks,

**Comment by ValWood** [comment]
corrected above.

**Comment by nataled** [comment]
Hi Val,

Your term is given below:

PR:000050562 = tif211/Phos:(S52)

[Term]
id: PR:000050562
name: eukaryotic translation initiation factor 2 subunit alpha phosphorylated 1 (Schizosaccharomyces pombe)
def: "A eukaryotic translation initiation factor 2 subunit alpha (Schizosaccharomyces pombe) that has been phosphorylated at the position equivalent to Ser-52 of the amino acid sequence represented by UniProtKB:P56286. UniProtKB:P56286, Ser-52, MOD:00046." [PRO:DAN, PomBase:VW, PMID:28771613]
comment: Category=organism-modification. Requested_by=PomBase. Kinase=("GCN2"; PR:000050561; Ser-52).
synonym: "Spom-EIF2S1/Phos:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:P56286, Ser-52, MOD:00046" EXACT PRO-proteoform-std [PRO:DNx]
synonym: "UniProtKB:P56286-1, Ser-52, MOD:00046" NARROW PRO-proteoform-std [PRO:DNx]
is_a: PR:000050560 ! eukaryotic translation initiation factor 2 subunit alpha (Schizosaccharomyces pombe)
relationship: has_part MOD:00046 ! O-phospho-L-serine
relationship: only_in_taxon NCBITaxon:9606 ! Homo sapiens
