### ISSUE TITLE
Term issue: gene level parent term for Spata33 organism-gene terms

### ISSUE THREAD

**Issue by krchristie** [PROconsortium/PRoteinOntology#262]
Hi,

It looks like we need a gene level parent term for the Spata33 proteins, e.g. human SPATA33 and mouse Spata33:

> [Term]
> id: PR:Q96N06
> name: spermatogenesis-associated protein 33 (human)
> def: "A protein that is a translation product of the SPATA33 gene in human." [PRO:DNx, UniProtKB:Q96N06]
> comment: Category=organism-gene.
> synonym: "SPATA33" RELATED Gene-based [UniProtKB:Q96N06]
> synonym: "C16orf55" RELATED Gene-based [UniProtKB:Q96N06]
> synonym: "hSPATA33" EXACT PRO-short-label [PRO:DNx]
> xref: UniProtKB:Q96N06
> intersection_of: has_gene_template HGNC:26463 ! SPATA33 (human)
> intersection_of: only_in_taxon NCBITaxon:9606 ! Homo sapiens
> **intersection_of: PR:000000001 ! protein**
> 
> [Term]
> id: PR:Q8C624
> name: spermatogenesis-associated protein 33 (mouse)
> def: "A protein that is a translation product of the Spata33 gene in mouse." [PRO:DNx, UniProtKB:Q8C624]
> comment: Category=organism-gene.
> synonym: "Spata33" RELATED Gene-based [UniProtKB:Q8C624]
> synonym: "mSpata33" EXACT PRO-short-label [PRO:DNx]
> xref: UniProtKB:Q8C624
> intersection_of: has_gene_template MGI:2444920 ! Spata33 (mouse)
> intersection_of: only_in_taxon NCBITaxon:10090 ! Mus musculus
> **intersection_of: PR:000000001 ! protein**

Both the Alliance pages for mouse & human:
https://www.alliancegenome.org/gene/MGI:2444920
https://www.alliancegenome.org/gene/HGNC:26463

and the Panther page for the Spata33 family
http://www.pantherdb.org/panther/family.do?clsAccession=PTHR38649:SF1

indicate that these are orthologs.

Thanks,

-Karen

**Comment by nataled** [comment]
Hi Karen,

Is something amiss? I just saw your emoji (unfortunately, notifications aren't sent for reactions).

**Comment by krchristie** [comment]
> Hi Karen,
> 
> Is something amiss? I just saw your emoji (unfortunately, notifications aren't sent for reactions).

Hi Darren, no all is good. The emoji was my reaction during our initial exchange, and meant to convey satisfaction that the term is created. Good to know that notifications aren't sent for reactions.

Thanks,

Karen

**Comment by nataled** [comment]
Oh, glad to hear you're satisfied! Mousing over the emoji indicated it as meaning 'confused' (though, to my eye, it looks more like 'disappointed').

**Comment by krchristie** [comment]
> Oh, glad to hear you're satisfied! Mousing over the emoji indicated it as meaning 'confused' (though, to my eye, it looks more like 'disappointed').

Oh, sorry, I blame my presbyopia. I thought it was the smiley face emoji. I agree that the one I actually selected looks more like disappointed than confused.

**Comment by krchristie** [comment]
> Revision: I somehow missed that the indicated identifier was reserved for another term. I've revised it to PR:000050571.

Thanks for the FYI
