### ISSUE TITLE
Term issue: XBP1 hierarchy issues

### ISSUE THREAD

**Issue by krchristie** [PROconsortium/PRoteinOntology#266]
Hi Darren,

I was looking at XBP1 proteins and noticed a couple issues, both visible on the hierarchy:

![20220104-Xbp1-PROhierarchy](https://user-images.githubusercontent.com/10533218/148125278-55f6b8e9-d8cb-4b40-8a07-61799d1366a6.png)

**1. parent term for PR:O35426 - X-box-binding protein 1 (mouse)**

The organism gene term for mouse, **PR:O35426**, should be but is NOT a child term of the gene level term: **PR:000017476** - X-box-binding protein 1

Action item: Please add **PR:000017476 - X-box-binding protein 1** as a parent term of **PR:O35426 - X-box-binding protein 1 (mouse)**

Thanks, 

Karen

I also noticed this second issue:

**2. classification of PR:Q9R1S4-1 - X-box-binding protein 1 isoform r1 (rat)**

It seems extremely likely that rat isoform 1 should be classified under the sequence level term **PR:000037222 | X-box-binding protein 1 isoform 1**. XBP1 is highly conserved in mammals and the rat sequences is an extremely good match for the mouse sequences, including a TrEMBL record for rat isoform 2 (A0A140TAA7_RAT) that is currently computationally mapped to the rat SwisProt sequence for XBP1: Q9R1S4. 

I don't know if the alignment is enough evidence for PRO, but here's an alignment showing both isoform sequences for human, mouse, and rat. It's out of my purview to investigate any further if there is experimental evidence for UniProt to merge A0A140TAA7_RAT into Q9R1S4, so if this isn't enough evidence for PRO, it would be up to RGD curators to follow up on this if they are interested.

![20220104-XBP1-HsMmRn-align](https://user-images.githubusercontent.com/10533218/148127267-29af93ca-d3d1-4e51-9223-2b1937df8500.png)

**Comment by nataled** [comment]
Hi Karen,

I agree with all your assertions. The requisite changes have been made, and will appear (via the web interface) in the next release.

Best regards,
Darren

**Comment by krchristie** [comment]
Hi Darren,

Is there an expected date for the next release?

I'd like to set myself a reminder at an appropriate time to check if this change has propagated to the MGI web site.

Thanks,

-Karen

**Comment by nataled** [comment]
We generally release approximately quarterly, and the last one was toward the end of last month. So likely March/April.

I'm not sure what it takes to propagate changes at MGI. It might propagate sooner when I upload the interim file (http://purl.obolibrary.org/obo/pr/pr-dev.obo; see https://proconsortium.org/pro_comm_prerelease.shtml for others), which is done upon changes (indeed, the interim file has already been uploaded).
