### ISSUE TITLE
Term issue:  SARS-CoV-2 orf9c

### ISSUE THREAD

**Issue by yongqunh** [PROconsortium/PRoteinOntology#273]
Currently PR has orf9b, but does not have the SARS-CoV-2 orf9c.

See:
[severe acute respiratory syndrome coronavirus 2 protein]
http://purl.obolibrary.org/obo/PR_000050262
In Ontobee: https://www.ontobee.org/ontology/PR?iri=http://purl.obolibrary.org/obo/PR_000050262

Currently classified as a putative protein in UniProt:
https://www.uniprot.org/uniprot/P0DTD3

However, there are over 10 papers now in PubMed:
https://pubmed.ncbi.nlm.nih.gov/?term=SARS-CoV-2+orf9c&sort=date
Our CIDO protein-protein interactoin annotation needs this protein since the following Nature paper studied this protein:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7431030/
(see Fig. 3, for example)

**Comment by nataled** [comment]
Hi Oliver,
This term actually does already exist in PRO, but under its original name "uncharacterized protein 14". Given the update that you pointed out, I have revised the term to take this into account (see OBO stanza below) and added the appropriate synonyms. The PURL for this term is http://purl.obolibrary.org/obo/PR_P0DTD3-1.

Note: though the changes have been made internally, you won't see them on our site (or yours) until the next release.

[Term]
id: PR:P0DTD3-1
name: putative ORF9c protein (SARS-CoV-2)
alt_id: PR:P0DTD3
def: "An N gene translation product (SARS-CoV-2) that is encoded by the ORF9c reading frame, giving rise to a protein with the amino acid sequence represented by UniProtKB:P0DTD3-1." [PRO:DAN, UniProtKB:P0DTD3]
comment: Category=organism-sequence. Note: 73 aa protein.
synonym: "N/iso:ORF9c (SARS2)" EXACT PRO-short-label [PRO:DAN]
synonym: "N/iso:ORF14 (SARS2)" EXACT [PRO:DAN]
synonym: "PRO_0000449658" EXACT PRO-proteoform-ftid [PRO:DAN]
synonym: "uncharacterized protein 14 (SARS-CoV-2)" EXACT [UniProtKB:P0DTD3]
synonym: "ORF9c (SARS-CoV-2)" EXACT [UniProtKB:P0DTD3]
xref: UniProtKB:P0DTD3-1
is_a: PR:000050387 ! N gene translation product (SARS-CoV-2)
relationship: only_in_taxon NCBITaxon:2697049 ! Severe acute respiratory syndrome coronavirus 2

**Comment by yongqunh** [comment]
Got it. Thanks!
