### ISSUE TITLE
Term issue:  Phospho dites for Rec8 (meiotic cohesin complex kleisin subunit )

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#276]
Rec8 
P36626

S-450 Phosphorylated (added by plo1)
S-412 Phosphorylated  (added by hhp1 (pombe Ck1), (removed by by ppa2)
S-412 UnPhosphorylated  

https://www.pombase.org/reference/PMID:33888556

note that the P sites do not co-occur (antagonistic)

CC @manulera I will  use this as an example for the configuration for PTModifications next time we chat

**Comment by nataled** [comment]
Hi Val,

A few of these were previously requested:
S-450 Phosphorylated (added by plo1)
   PR:000050511 (asserts only that S-450 is phosphorylated, but silent on any other position)
   PR:000050512 (asserts that S-450 is phosphorylated and that S-412 is NOT phosphorylated)
S-412 Phosphorylated (added by hhp1 (pombe Ck1), (removed by by ppa2)
   PR:000050513 (asserts only that S-412 is phosphorylated, but silent on any other position)

I can make the S-412 UnPhosphorylated, but this begs the questions:
1) Is the intention to have a form that is not phosphorylated at either site?
2) Do you also want something like PR:000050512, but with the states swapped (phosphorylated on 412 but not on 450)?

**Comment by ValWood** [comment]
forgot I had already requested, so I must have just forgotten to add them.

I only need  the ones that I already requested to model this.
