### ISSUE TITLE
Term issue: uniquitinated form of Any1

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#280]
Any1= SPBC18H10.20c/O60150

residue = K263
Added by Pub1 SPAC11G7.02 Q92462

[Q92462](https://research.bioinformatics.udel.edu/iptmnet/entry/Q92462/)

PMID:24876389
--
Title | Fission yeast arrestin-related trafficking adaptor, Arn1/Any1, is ubiquitinated by Pub1 E3 ligase and regulates endocytosis of Cat1 amino acid transporter.
Authors | Nakashima A, Kamada S, Tamanoi F, Kikkawa U

**Comment by nataled** [comment]
Here is your term:

any1/(Ubiq):Lys263

I used "mutation phenotype evidence" for the modification evidence. Let me know if that's incorrect.

[Term]
id: PR:000059591
name: arrestin-related substrate adaptor Any1 ubiquitinated 1 (Schizosaccharomyces pombe)
def: "An arrestin-related substrate adaptor Any1 (Schizosaccharomyces pombe) that has been ubiquitinated at the position equivalent to Lys-263 of the amino acid sequence represented by UniProtKB:O60150. Example: UniProtKB:O60150, Lys-263, MOD:01148." [PRO:DAN, PomBase:VW, PMID:24876389]
comment: Category=organism-modification. Requested by=PomBase. UbLigase=("pub1"; PR:000059588; Lys-263). Evidence=(ECO:0000015, based on PMID:24876389).
synonym: "Spom-any1/Ubiq:1" EXACT PRO-short-label [PRO:DNx]
synonym: "UniProtKB:O60150, Lys-263, MOD:01148" EXACT PRO-proteoform-std [PRO:DAN]
is_a: PR:000059590 ! arrestin-related substrate adaptor Any1 (Schizosaccharomyces pombe)
relationship: has_part MOD:01148 ! ubiquitinylated lysine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe
