### ISSUE TITLE
Revision needed on "Linking to PRO Terms and Files" page

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#282]
Since the wiki page has been retired, the following page needs revision:

https://proconsortium.org/pro_comm_PURL.shtml

On this page, please replace
"http://purl.obolibrary.org/obo/pr/wiki points to the PRO wiki (on which this page is kept)"
with
"http://purl.obolibrary.org/obo/pr/docs points to PRO documentation (on which this page is kept)"

Obviously the link will need changing as well. Thanks!

**Comment by jz26** [comment]
done.
