### ISSUE TITLE
Term issue: O60187/sid4. Ubiquitated

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#284]
To model
https://pubmed.ncbi.nlm.nih.gov/21131906/

I need 
sid4 (ubiquitinated) and sid4 (un-ubiquitinated).

From this paper, I don't  know the exact residues

(although minimally PMID:26412298  K144, K386, K517, K565)

**Comment by ValWood** [comment]
Also a phosphorylated version of Sid4 T275 and S278 

Thus, phosphorylation on
both T275 and S278 is necessary and sufficient to support binding of the Dma1 FHA
domain to Sid4 and Sid4 ubiquitination.
PMID:24055157

**Comment by nataled** [comment]
Hi Val,
Regarding the ubiquitin-modified version of sid4, did you want:
1) a single term for ubiquitin at any site(s), or
2) a single term for ubiquitin at the 4 sites indicated. or
3) two terms, one for the general and one for the specific?

**Comment by ValWood** [comment]
Yes, let's go with 

Sid4 PT275,S278  (we know these are the *only* required sites
and
Sid4 PT275,S278 -Ub (general). 
I can update this with more info about the necessary/sufficient sites later.

**Comment by nataled** [comment]
It turns out that those two proteoforms were already created some years ago as part of ticket #139:
PR:000044611 = sid4/Phos:(T275/S278)
PR:000044612 = sid4/Phos:(T275/S278)Ubiq:(+)

**Comment by ValWood** [comment]
Brilliant thanks, I must have forgotten to plug them in.
Val
