### ISSUE TITLE
Term issue: Create more Dicty histone mod terms

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#295]
RACE-PRO reference numbers
REF541716_Q76NW2
REF872405_O15819
REF37396_Q54WG6
REF50649_Q55BN9
REF904833_Q54WG6

**Comment by nataled** [comment]
Hi @pfey03,

Your terms are ready. As before, they are usable now, but won't appear in the downloadable ontology file until the next release (which is in progress). Please let me know if there is anything amiss. Thanks!

<pre>REF541716_Q76NW2 = PR:000060208
REF872405_O15819 = PR:000060209
REF37396_Q54WG6 = PR:000060210
REF50649_Q55BN9 = PR:000060211
REF904833_Q54WG6 = PR:000060212

[Term]
id: PR:000060208
name: histone H4 acetylated 2 (Dictyostelium discoideum)
def: "A histone H4 (Dictyostelium discoideum) that has been acetylated at the position equivalent to Lys-22 of the amino acid sequence represented by UniProtKB:Q76NW2. Note that the indicated residue is called Lys-21 in the literature, based on sequence numbering that accounts for a removed initiator methionine. UniProtKB:Q76NW2, Lys-22, MOD:00064." [PRO:DAN, PMID:33947439, dictyBase:PF]
comment: Category=organism-modification. Requested by=dictyBase. Note: In vivo. Contains H4K21ac.
synonym: "Dicty-H4/Ac:2" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q76NW2, Lys-22, MOD:00064" EXACT PRO-proteoform-std [PRO:DAN]
is_a: PR:Q76NW2 ! histone H4 (Dictyostelium discoideum)
relationship: has_part MOD:00064 ! N6-acetyl-L-lysine
relationship: only_in_taxon NCBITaxon:44689 ! Dictyostelium discoideum

[Term]
id: PR:000060209
name: histone H3.3 type a trimethylated 1, acetylated tail form (Dictyostelium discoideum)
def: "A histone H3.3 type a (Dictyostelium discoideum) that has been trimethylated at the position equivalent to Lys-5 of the amino acid sequence represented by UniProtKB:Q55BN9, and that has been acetylated on one or more additional lysine residues within the N-terminal tail region. Note that the indicated residue is called Lys-4 in the literature, based on sequence numbering that accounts for a removed initiator methionine. UniProtKB:O15819, Lys-5, MOD:00083|MOD:00064." [PRO:DAN, PMID:22600736, dictyBase:PF]
comment: Category=organism-modification. Requested by=dictyBase. Enzyme=("set1"; PR:Q54HS3, Lys-5). Evidence=(ECO:0000006, based on PMID:22600736). Note: In vivo. Contains H3aK4me3 (or, broadly, H3K4me3).
synonym: "Dicty-H3a/AcMe3:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:O15819, Lys-5, MOD:00083|MOD:00064" BROAD PRO-proteoform-std [PRO:DAN]
is_a: PR:O15819 ! histone H3.3 type a (Dictyostelium discoideum)
relationship: has_part MOD:00083 ! N6,N6,N6-trimethyl-L-lysine
relationship: has_part MOD:00064 ! N6-acetyl-L-lysine
relationship: only_in_taxon NCBITaxon:44689 ! Dictyostelium discoideum

[Term]
id: PR:000060210
name: histone H2AX acetylated and dimethylated 1 (Dictyostelium discoideum)
def: "A histone H2AX (Dictyostelium discoideum) that has been acetylated at the position equivalent to Ser-2 and dimethylated at the position equivalent to Lys-10 of the amino acid sequence represented by UniProtKB:Q54WG6. Note that the indicated residues are called Ser-1 and Lys-9, respectively, in the literature, based on sequence numbering that accounts for a removed initiator methionine. UniProtKB:Q54WG6, Ser-2, MOD:00647|Lys-10, MOD:00084." [PRO:DAN, PMID:33947439, dictyBase:PF]
comment: Category=organism-modification. Requested by=dictyBase. Note: In vivo. Contains H2AXS1ac and H2AXK9me2.
synonym: "Dicty-H2AX/AcMe2:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q54WG6, Ser-2, MOD:00647|Lys-10, MOD:00084" EXACT PRO-proteoform-std [PRO:DAN]
is_a: PR:Q54WG6 ! histone H2AX (Dictyostelium discoideum)
relationship: has_part MOD:00647 ! monoacetylated L-serine
relationship: has_part MOD:00084 ! N6,N6-dimethyl-L-lysine
relationship: only_in_taxon NCBITaxon:44689 ! Dictyostelium discoideum

[Term]
id: PR:000060211
name: histone H3.3 type b acetylated 3 (Dictyostelium discoideum)
def: "A histone H3.3 type b (Dictyostelium discoideum) that has been acetylated at the position equivalent to Lys-10 of the amino acid sequence represented by UniProtKB:Q55BN9. Note that the indicated residue is called Lys-9 in the literature, based on sequence numbering that accounts for a removed initiator methionine. UniProtKB:Q55BN9, Lys-10, MOD:00064." [PRO:DAN, PMID:22600736, dictyBase:PF]
comment: Category=organism-modification. Requested by=dictyBase. Note: In vivo. Contains H3bK14ac (or, broadly, H3K14ac). Histone H3a does not obtain the corresponding modification.
synonym: "Dicty-H3b/Ac:3" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q55BN9, Lys-10, MOD:00064" EXACT PRO-proteoform-std [PRO:DAN]
is_a: PR:Q55BN9 ! histone H3.3 type b (Dictyostelium discoideum)
relationship: has_part MOD:00064 ! N6-acetyl-L-lysine
relationship: only_in_taxon NCBITaxon:44689 ! Dictyostelium discoideum

[Term]
id: PR:000060212
name: histone H2AX acetylated, dimethylated, and monomethylated 1 (Dictyostelium discoideum)
def: "A histone H2AX (Dictyostelium discoideum) that has been dimethylated at the positions equivalent to Ser-9 and Lys-10, monomethylated at the position equivalent to Lys-18, and acetylated at the position equivalent to Lys-19 of the amino acid sequence represented by UniProtKB:Q54WG6. Note that the indicated residues are called Ser-8, Lys-9, Lys-17, and Lys-18, respectively, in the literature, based on sequence numbering that accounts for a removed initiator methionine. UniProtKB:Q54WG6, Ser-9, MOD:01783|Lys-10, MOD:00084|Lys-18, MOD:00085|Lys-19, MOD:00064." [PRO:DAN, PMID:33947439, dictyBase:PF]
comment: Category=organism-modification. Requested by=dictyBase. Note: In vivo. Contains H2AXS8me2, H2AXK9me2, H2AXK17me1, and H2AXK18ac.
synonym: "Dicty-H2AX/AcMe1Me2:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q54WG6, Ser-9, MOD:01783|Lys-10, MOD:00084|Lys-18, MOD:00085|Lys-19, MOD:00064" EXACT PRO-proteoform-std [PRO:DAN]
is_a: PR:Q54WG6 ! histone H2AX (Dictyostelium discoideum)
relationship: has_part MOD:01783 ! N,N-dimethyl-L-serine
relationship: has_part MOD:00084 ! N6,N6-methyl-L-lysine
relationship: has_part MOD:00085 ! N6-methyl-L-lysine
relationship: has_part MOD:00064 ! N6-acetyl-L-lysine
relationship: only_in_taxon NCBITaxon:44689 ! Dictyostelium discoideum

</pre>

**Comment by pfey03** [comment]
Wow that's fast, thanks Darren. I had a long Flamenco class tonight I will check it out tomorrow

**Comment by pfey03** [comment]
@nataled 
PR:000060209: probably my mistake, the first UniProt ID is H3b not H3a, please change it to UniProt:O15819

PR:000060211: you have: Contains H3bK14ac (or, broadly, H3K14ac). But this is wrong, see text above, it should be:
Contains H3bK9ac (or broadly) H3K9ac (although this doesn't much occur on H3a). Did I make this mistake? If so I'm sorry.

**Comment by nataled** [comment]
@pfey03 thanks for the feedback. Both are fixed in the development version (still working on the release). BTW, those errors were mine. Realizing that this set of terms could be more quickly created by copying other terms and making changes, I opted to do that method but missed a few things.
