### ISSUE TITLE
Implement GPI display for new PRO terms not yet in database

### ISSUE THREAD

**Issue by nataled** [PROconsortium/PRoteinOntology#296]
A recent example of such an entry is https://proconsortium.org/cgi-bin/entry_pro?id=PR%3A000060211&retrieve.x=9&retrieve.y=8

First, where the link should be displayed. The link should be next to 'Show OBO stanza', like:
Show OBO stanza / GPI
An example is on the test site already:
https://proconsortium.org/app_test/entry/PR:000025934/

The information to display will come from a file called a GPI file (Gene Product Information; it is used by the GO consortium). This file has a header that will need to be display along with the information. Currently, the header for the term given at the very top should look like this:

<pre>
!gpi-version: 2.0
!namespace: PR
!generated-by: PR
!date-generated: 2022-11-29
!!
!! From: pro.obo (2022-08-08) as updated by pro_wv.obo (2022-11-29)
!!
!! Columns:
!!
!!   Col#  name                                cardinality   Note
!!    1    DB_Object_ID                        1             
!!    2    DB_Object_Symbol                    1             Based on the PRO-short-label
!!    3    DB_Object_Name                      0 or greater  
!!    4    DB_Object_Synonyms                  0 or greater  Only exact synonyms are given
!!    5    DB_Object_Type                      1             Will always be PR:000000001 (protein) or GO:0032991 (protein-containing complex) for PRO terms
!!    6    DB_Object_Taxon                     1             
!!    7    Encoded_By                          0 or greater  The gene(s) encoding the DB_Object_ID; multiple genes are separated by pipes
!!    8    Parent_Protein                      0 or greater  Blank if DB_Object_ID refers to a canonical entity, otherwise it will be an ancestral identifier (in the ontological sense) that refers to the canonical entity class.
!!    9    Protein_Containing_Complex_Members  0 or greater  
!!   10    DB_Xref(s)                          0 or greater  Database entries that correspond to the PRO term (UniProtKB, Reactome)
!!   11    Gene_Product_Properties             0 or greater  Blank (not populated in PRO gpi files)
!!
</pre>

The full header in that file (all of which begin with an exclamation point) also has Example information that we do NOT want to display, so the part we want will have to be parsed out of the GPI file. To do this, all lines beginning with an exclamation point that comes after the first 'Example:' line should be ignored.

We then want to display the single line that contains the GPI information for the indicated term. Yes, it's just one line. It won't look so great because of all the header info, but unfortunately we need to show that info. The single line can be grepped from the file if desired (it will begin with the PRO identifier, so a grep for ^PR:000060211 will do the trick.

As for the location of the file, it is the one found at https://proconsortium.org/download/development/pro_wv.gpi

The indicated file is uploaded between releases, whenever a new term is added to PRO. Let me know if you have questions. @Julie-Cowart already implemented this for the main entry pages so she can guide you on how she approached it. Otherwise, ask me.

**Comment by jz26** [comment]
Done.

**Comment by nataled** [comment]
Looks great, thanks! One thing I neglected to mention is that there will only be a GPI entry if the PRO term has an organism associated with it, meaning it must have 'NCBITaxon' somewhere in the stanza. It isn't a big deal if you can't, but if possible can you suppress the GPI link when there is no taxon? Maybe an easier way to do it is to suppress if there is no result (other than the header).

**Comment by jz26** [comment]
Done, but can't find examples to test.

**Comment by nataled** [comment]
I made a special temporary term to try. Works perfectly, thanks!
