### ISSUE TITLE
Term issue: Palmytoilation sites of tht1

### ISSUE THREAD

**Issue by manulera** [PROconsortium/PRoteinOntology#299]
Gene name in pombe: tht1
Uniprot id: Q09684
Rerefence: PMID:36650056

We want to request an id for tht1 palmitoylated on both C65 and C78

* S-palmitoylation (reversible) is added at Cysteine C65, C78
    * there is mass-spec evidence for this (Fig. 4F)

* ark1 (palmitoyl-transferase) is at least partially responsible for this, as deletion of ark1 leads to lower tht1 palmitoylated fraction, tested with biochemistry in Fig. 4E.

cc @ValWood

Let me know if you need more information.

Thanks,
Manu

**Comment by nataled** [comment]
Hi Manuel,
Thank you for your request. Your term is given below. It is active and usable now, but won't appear in the downloadable version of PRO until the next release (in progress).

[Term]
id: PR:000060241
name: nuclear fusion protein tht1 palmitoylated 1 (Schizosaccharomyces pombe)
def: "A nuclear fusion protein tht1 (Schizosaccharomyces pombe) that has been palmitoylated at positions equivalent to Cys-65 and Cys-78 of the amino acid sequence represented by UniProtKB:Q09684. Example: UniProtKB:Q09684, Cys-65/Cys-78, MOD:00047." [PRO:DAN, PomBase:MLR, PMID:36650056]
comment: Category=organism-modification. Requested by=PomBase. Palmitoylase=("ark1"; PR:000060242; Cys-65/Cys-78). Evidence=(ECO:0001091, based on PMID:36650056).
synonym: "Spom-tht1/Palm:1" EXACT PRO-short-label [PRO:DAN]
synonym: "UniProtKB:Q09684, Cys-65/Cys-78, MOD:00115" NARROW PRO-proteoform-std [PRO:DAN]
is_a: PR:000060240 ! nuclear fusion protein tht1 (Schizosaccharomyces pombe)
relationship: has_part MOD:00115 ! S-palmitoyl-L-cysteine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by manulera** [comment]
Thanks @nataled that was really fast! Next time I will provide more info, like the ECO codes etc. Do you have a full template / list of things you need?

**Comment by nataled** [comment]
@manulera you pretty much already provide everything needed, though the ECO code would be very much appreciated (as opposed to which figure in the paper is relevant). As I don't regularly do annotation, I don't have great familiarity with the nuances. I'm hoping I got this one right!

**Comment by manulera** [comment]
Yes! It's all good. Thanks again for the very fast addition 🚀🚀🚀

**Comment by nataled** [comment]
You're very welcome!

**Comment by nataled** [comment]
I just realized that the version I pasted lacked a correction I made in my final version. On the definition line, the PSI-MOD identifier is incorrectly given as MOD:00047. It should be MOD:00115. I edited my comment accordingly.

**Comment by nataled** [comment]
Correction made 2023-11-13: The enzyme involved is akr1, not ark1. This will change the comment line in PR:000060241 to show the palmitoylase as PR:000064864 "palmitoyltransferase akr1 (Schizosaccharomyces pombe)" instead of PR:000060242.
