### ISSUE TITLE
Term issue: adding terms for the EGFR with bound ligand

### ISSUE THREAD

**Issue by giacomodecolle** [PROconsortium/PRoteinOntology#305]
We would like to request the following two terms for the PRotein Ontology in support of our work on the PRotein Conformation ontology.

epidermal growth factor receptor-EGF bound form

definition: A plasma membrane protein-containing complex formed through the binding of an epidermal growth factor receptor, signal peptide removed form to its ligand epidermal growth factor.
'has part' some 'epidermal growth factor receptor, signal peptide removed form' and 'has part' some 'pro-epidermal growth factor'

We have also noticed that there is no generic version of the pro-epidermal growth factor with signal peptide removed, so we are using the parent term for the previous axiom.

epidermal growth factor receptor-EGF bound form dimer

definition: A plasma membrane protein-containing complex that is a dimer of epidermal growth factor receptor-EGF bound form.
'has part' some 'epidermal growth factor receptor-EGF bound form' 

Thanks,
Giacomo and @addiehl

**Comment by nataled** [comment]
Hi Giacomo,
Is the form of EGF that you want bound to EGFR the pro-EGF with signal peptide removed? I would expect it to be the fully processed form (for which no PRO term yet exists), that corresponds to (in human) the P01133 sequence from 971-1023. Please confirm.

**Comment by nataled** [comment]
Just in case I'm correct in my assumption, I created the following four terms (OBO format), the latter two of which are what I think you want:

PR:000060268 pro-epidermal growth factor (this is the generalized EGF-without-signal peptide)
PR:000060269 epidermal growth factor (this is the mature form bound by EGFR)
PR:000060270 epidermal growth factor receptor, EGF-bound form monomer
PR:000060271 epidermal growth factor receptor, EGF-bound form dimer (the active form)

Let me know if you need bound forms of EGFR with something more than just the mature EGF.

[Term]
id: PR:000060268
name: pro-epidermal growth factor
def: "A pre-pro-epidermal growth factor that has had the signal peptide removed. Example: UniProtKB:P01133, 23-1207." [PRO:DAN]
comment: Category=modification.
synonym: "EGF/SigPep-" EXACT PRO-short-label [PRO:DAN]
synonym: "pro-EGF" EXACT [PRO:DAN]
intersection_of: PR:000006928 ! pre-pro-epidermal growth factor
intersection_of: lacks_part SO:0000418 ! signal_peptide

[Term]
id: PR:000060269
name: epidermal growth factor
def: "A pro-epidermal growth factor that has been cleaved to release an extracelluar 53aa segment proximal to the cell membrane. Example: UniProtKB:P01133, 971-1023." [PRO:DAN]
comment: Category=modification.
synonym: "EGF" EXACT PRO-short-label [PRO:DAN]
synonym: "urogastrone" EXACT PRO-short-label [PRO:DAN]
is_a: PR:000060268 ! pro-epidermal growth factor
relationship: output_of GO:0016485 ! protein processing

[Term]
id: PR:000060270
name: epidermal growth factor receptor, EGF-bound form monomer
def: "A plasma membrane protein complex that is formed through the binding of a membrane-bound epidermal growth factor receptor, signal peptide removed form to its ligand epidermal growth factor." [PRO:GDC, PRO:DAN]
comment: Category=complex.
synonym: "EGFR/EGF monomer" EXACT [PRO:DAN]
is_a: GO:0098797 ! plasma membrane protein complex
relationship: has_component PR:000019753 {cardinality="1"} ! epidermal growth factor receptor, signal peptide removed form
relationship: has_component PR:000060269 {cardinality="1"} ! epidermal growth factor

[Term]
id: PR:000060271
name: epidermal growth factor receptor, EGF-bound form dimer
def: "A plasma membrane protein complex that is formed through the dimerization of epidermal growth factor receptor, EGF-bound form monomers." [PRO:GDC, PRO:DAN]
omment: Category=complex.
synonym: "EGFR/EGF dimer" EXACT [PRO:DAN]
is_a: GO:0098797 ! plasma membrane protein complex
relationship: has_component PR:000060270 {cardinality="2"} ! epidermal growth factor receptor, EGF-bound form monomer

**Comment by nataled** [comment]
There seems to be multiple models of how EGFR is activated. The above terms were made following what appears to be the 'ligand-induced dimerization' model, where ligand-bound monomers dimerize. The other model ('rotation model"; see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5492017/) presupposes that the dimer exists in an inactive state, and the ligand binding serves to activate via conformational change.

If you wish to model the rotation mechanism as well, I'll need to make a dimerized form of EGFR that lacks any ligand. Such a form would also work as the basis for binding to other ligands as well.

**Comment by giacomodecolle** [comment]
Hi Darren,

thank you for adding the terms, they are indeed what we were looking for. 
Regarding the "rotation model", it seems that it has emerged in more recent years, and for this reason it was not our first choice to build an ontological representation. We are currently checking our classes with this model and evaluating how to properly introduce this representation of the EGFR in the future. Thanks for the reference!

Giacomo
