### ISSUE TITLE
Term issue: phosphorylated and unphosphorylated dis1

### ISSUE THREAD

**Issue by manulera** [PROconsortium/PRoteinOntology#310]
Dear @nataled,

I would like to request two terms for the phosphorylated and unphosphorylated forms of dis1 protein (SPCC736.14)

Gene name in pombe: dis1
Uniprot id: Q09933
Rerefence: PMID:34080538

* The phosphorylated sites were discovered in PMID:16920624 as Cdc2 consensus sites 
* The phosphorylated residues are: T279,S293,S300,S551,S556,S590
* The only site confirmed experimentally is S551, that they detected with an antibody (Fig. 1 C)
* Experiments with phosphomimmetic and phospho-dead mutants at the proposed positions support that some of them are indeed phosphorylated / dephosphorylated, but not sure if this is sufficient evidence to add all of them in the term.
* Phenotypes of clp1D mutants in PMID:34080538 supports that clp1 dephosphorylates dis1
* No direct experimental evidence supports that cdc2 phosphorylates dis1, but given the consensus sequence and the timing, it's probably the case.

This is the info that I have, so not sure if it's enough to support phosphorylation at T279,S293,S300,S551,S556,S590. If not, "phosphorylated form" and "unphosphorylated form" are enough.

cc: @ValWood

**Comment by nataled** [comment]
Hi Manuel,
There are two terms already in PRO for the specific modifications mentioned:
1) PR:000050503 is the term for dis1 phosphorylated on all the specific sites indicated.
2) PR:000050504 is the term for dis1 NOT phosphorylated on the specific sites indicated.

Do you still need the generic phos/unphos forms?

**Comment by manulera** [comment]
Ooops! I thought they did not exist because they had no GO annotations. I will use those then, sorry and thanks for checking.
