### ISSUE TITLE
Term issue: rpb1 Phos:CTD-S2 (P36594)

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#315]
I'm not sure if this exists, when I search on  forms for P36594

https://proconsortium.org/app/entry/PR:P36594/#forms
I do not see it, but also I don't see the generic Phos:CTD
https://proconsortium.org/app/entry/PR:000050494/

ref
https://www.pombase.org/reference/PMID:20605454
We show that phosphorylation of serine 2 (S2P) in the C-terminal domain of the largest subunit of the RNA polymerase II (PolII) enzyme by the Lsk1 cyclin-dependent kinase has only a minor impact on global gene expression during vegetative growth but is critical for the induction of ste11 transcription during sexual differentiation

added by  O14098

**Comment by nataled** [comment]
Hi Val,

Looking at the reference you provided, I see the following sentence in the first paragraph of the results:

"The S5A mutant was not efficiently phosphorylated by any of these kinases, suggesting that the presence of a serine residue in position 5 is important for S2 phosphorylation, as was recently observed for S7."

This seems to imply that you won't find pS2 in the absence of pS5 and/or pS7. In other words, if pS2 exists, it must be as pS2+pS5 or pS2+pS7 or pS2+pS5+pS7 (I didn't read the paper cited for the S7 effect, so I'm not sure about it). Complicating this supposition is the fact that this was an in vitro result and the multiple copies of the CTD repeat (so we don't know if the two or three phosphorylations must be within the same repeat, or if the pS5 and/or pS7 effects can occur 'across' repeats).

Given the above, should I created the pS2 version without other phosphorylations as requested, or do you want to look into it to see if a multiply-phosphorylated form should be created instead?
