### ISSUE TITLE
Term issue: Term issue: rpb1 Phos:CTD-T4 (P36594)

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#316]
rpb1 Phos:CTD-T4 (P36594)

https://www.pombase.org/reference/PMID:31276588
The S. pombe Pol2 CTD consists of tandem repeats of a heptapeptide Y1S2P3T4S5P6S7. CTD mutations S7A and S5A that prevent installation of the Ser7-PO4 or Ser5-PO4 marks de-repress pho1 and pho84 in phosphate-replete cells ([7](javascript:;),[8](javascript:;),[10](javascript:;),[13](javascript:;)). By contrast, prevention of the Thr4-PO4 mark by T4A hyper-represses pho1 and pho84 under phosphate-rich conditions ([7](javascript:;),[13](javascript:;)). Because such CTD mutations do not affect the activity of the lncRNA or mRNA gene promoters per se ([8](javascript:;),[10](javascript:;)), it is proposed that CTD status affects Pol2 termination during lncRNA synthesis (Figure [1A](javascript:;)). Specifically, it is hypothesized that loss of the Ser7-PO4 or Ser5-PO4 marks leads to precocious termination of prt lncRNA transcription prior to the pho1 promoter and loss of the Thr4-PO4 mark reduces termination and hence increases transcription across the pho1 promoter ([8](javascript:;))

I'm not sure which kinase yet...
I't might also be worth to add also  independent S7 and S5

**Comment by nataled** [comment]
Shall we close this one too?

**Comment by ValWood** [comment]
I'd still like this one so that I have a couple of curated exampes.

**Comment by nataled** [comment]
Okay, I will make this.

I notice that this one references a phosphorylation on the fourth position. Currently, the 'phosphorylated at the CTD' term, [PR:000050494](https://proconsortium.org/app/entry/PR:000050494/), does not include this, but probably it should. Do you agree? The definition of that term is "A DNA-directed RNA polymerase II subunit rpb1 (Schizosaccharomyces pombe) that has been phosphorylated at either the second, fifth, or seventh positions of one or more of the C-terminal heptad repeats (YSPTSPS)."

**Comment by ValWood** [comment]
I guess so if it is "OR"

This is the best overview I could find but it's 2016
https://www.nature.com/articles/nsmb.3285/figures/3

An older paper by the same  authors has a bit more information about which   combinations co-occur

https://www.semanticscholar.org/paper/Cracking-the-RNA-polymerase-II-CTD-code.-Egloff-Murphy/cc57d273d95c13959222178206e5d98a468be7a7/figure/3

and what they recruit
<img width="826" alt="Screenshot 2024-01-02 at 17 23 09" src="https://github.com/PROconsortium/PRoteinOntology/assets/7359272/4ceb989d-b920-4f9e-bb71-c357b52de191">

My aim is to get the versions which are known to recruit specific protein partners, but there isn't a great deal of evidence for fission yeast.

**Comment by nataled** [comment]
Hi Val,

The pT4 term has been created (see below). I also found that we already have the following:

pS2 - PR:000044738 DNA-directed RNA polymerase II subunit rpb1 phosphorylated 5 (Schizosaccharomyces pombe)
pS5 - PR:000044737 DNA-directed RNA polymerase II subunit rpb1 phosphorylated 3 (Schizosaccharomyces pombe)
pS7 - PR:000044739 DNA-directed RNA polymerase II subunit rpb1 phosphorylated 6 (Schizosaccharomyces pombe)

[Term]
id: PR:000064868
name: DNA-directed RNA polymerase II subunit rpb1 phosphorylated 7 (Schizosaccharomyces pombe)
def: "A DNA-directed RNA polymerase II subunit rpb1 CTD-phosphorylated form (Schizosaccharomyces pombe) that has been post-translationally modified to include phosphothreonine at the fourth position of one or more of the C-terminal heptad repeats (YSPTSPS)." [PRO:DAN, PomBase:VW, PMID:31276588]
comment: Category=organism-modification. Requested by=PomBase.
synonym: "Spom-rpb1/Phos:7" EXACT PRO-short-label [PRO:DAN]
synonym: "T4P-Pol II (Schizosaccharomyces pombe)" EXACT [PRO:DAN]
is_a: PR:000050494 ! DNA-directed RNA polymerase II subunit rpb1 CTD-phosphorylated form (Schizosaccharomyces pombe)
relationship: has_part MOD:00047 ! O-phospho-L-threonine
relationship: only_in_taxon NCBITaxon:4896 ! Schizosaccharomyces pombe

**Comment by ValWood** [comment]
Thanks!
I used these now, but do you know why I cant find them when I search using 
P36594?
v


[P36594](https://www.uniprot.org/uniprot/P36594)

**Comment by nataled** [comment]
Technically all PomBase requests are made to the species level, not strain (as used in UniProtKB). Most of the time, when making proteoform terms, I can use the strain numbering as an example, and in such cases I'd reference the UniProtKB accession. However, once in a while a term is created where there is no single proteoform described, as is the case here. When that happens, it creates a situation where specifying a single example would be very misleading, and so we avoid doing so.

The relevant terms can be found using this link:

https://lod.proconsortium.org/yasgui.html#query=PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>PREFIX owl:<http://www.w3.org/2002/07/owl#>PREFIX PomBase:<http://www.pombase.org/spombe/result/>PREFIX has_gene_template:<http://purl.obolibrary.org/obo/pr#has_gene_template>PREFIX oboInOwl:<http://www.geneontology.org/formats/oboInOwl#>PREFIX pr:<http://purl.obolibrary.org/obo/pr#>SELECT DISTINCT?PRO_term?Label FROM<http://purl.obolibrary.org/obo/pr>WHERE{VALUES?gn_id{PomBase:SPBC28F2.12}?PRO_term rdfs:subClassOf%2B?r.?r owl:onProperty has_gene_template:.?r owl:someValuesFrom?gn_id.?PRO_term rdfs:label?_Label.OPTIONAL{?gn_id rdfs:label?g}.bind(str(?_Label) as?Label)}ORDER BY ASC(?_PRO_short_label)%0A&endpoint=https://sparql.proconsortium.org/virtuoso/sparql&requestMethod=POST&tabTitle=Query&contentTypeConstruct=text/turtle,*/*;q=0.9&contentTypeSelect=application/sparql-results%2Bjson,*/*;q=0.9&outputFormat=table

Right around the middle of all this you'll see "{PomBase:SPBC28F2.12}". You can enter any PomBase gene accession in its place to see the relevant terms for that gene.

**Comment by ValWood** [comment]
I see this, but I don't see where to access the results?
<img width="1147" alt="Screenshot 2024-01-09 at 18 35 03" src="https://github.com/PROconsortium/PRoteinOntology/assets/7359272/341b7afd-7328-49d4-a4f9-7122578d21c8">

**Comment by nataled** [comment]
Ugh, I forgot that github will change things that are pasted unless I 'quote' it. Try this instead:
```
https://lod.proconsortium.org/yasgui.html#query=PREFIX rdf%3A %3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX rdfs%3A %3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX owl%3A %3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E  %0APREFIX PomBase%3A %3Chttp%3A%2F%2Fwww.pombase.org%2Fspombe%2Fresult%2F%3E%0APREFIX has_gene_template%3A %3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fpr%23has_gene_template%3E%0APREFIX oboInOwl%3A %3Chttp%3A%2F%2Fwww.geneontology.org%2Fformats%2FoboInOwl%23%3E%0ASELECT DISTINCT %3FPRO_term %3FLabel%0AFROM %3Chttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fpr%3E%0AWHERE%0A%7B%0A   VALUES %3Fgn_id %7B PomBase%3ASPBC28F2.12 %7D%0A   %3FPRO_term rdfs%3AsubClassOf%2B %3Fr . %0A   %3Fr owl%3AonProperty has_gene_template%3A . %0A   %3Fr owl%3AsomeValuesFrom %3Fgn_id . %0A   %3FPRO_term rdfs%3Alabel %3F_Label .%0A   OPTIONAL %7B%0A     %3Fgn_id rdfs%3Alabel %3Fg%0A   %7D .%0A   bind(str(%3F_Label) as %3FLabel)%0A%7D%0AORDER BY ASC(%3F_PRO_short_label)%0A&endpoint=https%3A%2F%2Fsparql.proconsortium.org%2Fvirtuoso%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*&q%3D0.9&q%3D0.9&outputFormat=table
```

**Comment by ValWood** [comment]
thanks!
