### ISSUE TITLE
PR:000050494

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#318]
<img width="1374" alt="fix at PRO" src="https://github.com/PROconsortium/PRoteinOntology/assets/7359272/30ea1cc2-3610-4373-a586-997374bb7bd3">

Hi @nataled , could the text here be changed slightly to 

A DNA-directed RNA polymerase II subunit rpb1 (Schizosaccharomyces pombe) that has been phosphorylated at ~either~ the second, fifth, ~or~ and seventh positions of one or more of the C-terminal heptad repeats (YSPTSPS). [[PMID:28367989](http://www.ncbi.nlm.nih.gov/pubmed/28367989), PRO:DAN, [PomBase:VW](http://www.pombase.org/spombe/result/VW)]

Here, the CTD code  is dependent on the 3 modifications occurring together (although  this may not always be present on every repeat)

**Comment by nataled** [comment]
Hi Val,
In my interim release version of PRO, the sentence also includes the fourth position: "A DNA-directed RNA polymerase II subunit rpb1 (Schizosaccharomyces pombe) that has been phosphorylated at either the second, fourth, fifth, and/or seventh positions of one or more of the C-terminal heptad repeats (YSPTSPS)." I assume there had to have been a request for that change previously. Should I merge the two changes, or remove the fourth position...?

**Comment by ValWood** [comment]
Actually, the paper I used for the initial one it is an 'or', although I suspect the 'activated' form is both. Let's leave this for now because the annotation as it is is correct, and I  know new papers are in the pipeline so I can refine with the correct combinations  to reflect the active code from those.

**Comment by nataled** [comment]
Ha! The same outcome as the last ticket about this term :)

**Comment by nataled** [comment]
There's no reason multiple versions can't exist, like one with the 'or' and one without.

**Comment by ValWood** [comment]
I think that might need to happen. I'm trying to piece together from multiple papers, but it isn't easy to interpret the experiments which depend on them mutating the residues in every repeat/ and or having very precise antibodies. 
I also know new papers are coming along, and that is a better point to review the existing annotation (things might change again, or become more precise)
