### ISSUE TITLE
Term issue: rpb1  CTD S7 modified 

### ISSUE THREAD

**Issue by ValWood** [PROconsortium/PRoteinOntology#325]
PMID:22508988

P36594 rpb1  CTD S7 modified (recruit Cdk9)

The preference of the conserved Cdk9 catalytic domain in fission yeast and metazoans for Ser7-modified CTD substrates, moreover, implies a conserved mechanism to impose order on the Pol II transcription cycle.

**Comment by nataled** [comment]
Term already exists: PR:000044739 but I've added the reference.
